/*
 * ncz-screensaver-idled - NCZ-OS screensaver idle timer daemon.
 *
 * Subscribes to ext-idle-notify-v1 on the Wayland session seat and fires three
 * notifications derived from the dev.ncz.screensaver GSettings schema:
 *
 *   - saver:   hack-idle-delay seconds   -> "ncz-screensaver start --idle"
 *              resumed                   -> "ncz-screensaver stop"
 *   - lock:    saver + lock-delay        -> stop the screensaver, then run
 *                                          the lock command (never twice
 *                                          concurrently)
 *   - dpms:    display-off-delay seconds -> zwlr-output-power off / on
 *
 * Plan rules (pure function, see plan_compute() below):
 *   - saver is disabled when mode == "off" (no animated hack).
 *   - lock is disabled when lock-enabled is false. When mode == "off" the lock
 *     happens at hack-idle-delay; otherwise it follows lock-delay after saver.
 *   - dpms is disabled when display-off-delay == 0.
 *
 * The daemon also listens for logind's PrepareForSleep and session Lock
 * signals, optionally holding a "delay" sleep inhibitor to keep the sleep
 * transition long enough for the lock command to spawn before it returns.
 *
 * All work happens on a single GLib main loop with a custom GSource that drives
 * the Wayland display; the daemon exits non-zero on disconnect so systemd can
 * restart it.
 *
 * Build deps (see launcher/meson.build): glib-2.0, gio-2.0, gio-unix-2.0,
 * wayland-client. The two ext-idle-notify-v1 and wlr-output-power-management
 * headers are generated from protocols XML files by wayland-scanner.
 */

#include <errno.h>
#include <fcntl.h>
#include <getopt.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>

#include <glib.h>
#include <glib-unix.h>
#include <gio/gio.h>
#include <gio/gunixfdlist.h>

#include <wayland-client.h>

/* Generated by wayland-scanner; defines the interface structs and the public
 * request/event helpers. */
#include "ext-idle-notify-v1-client-protocol.h"
#include "wlr-output-power-management-unstable-v1-client-protocol.h"

#define IDLED_VERSION  "ncz-screensaver-idled 0.1.0"
#define IDLED_LOG      "ncz-screensaver-idled: "
#define SETTINGS_SCHEMA_ID "dev.ncz.screensaver"

/* ------------------------------------------------------------------------- *
 * Logging
 * ------------------------------------------------------------------------- */

/* One bool, set by --verbose. Lines go to stderr with a fixed prefix so they
 * read cleanly in journalctl. */
static bool g_verbose = false;

static void idled_log(const char *level, const char *fmt, ...)
{
    char buf[1024];
    va_list ap;
    va_start(ap, fmt);
    g_vsnprintf(buf, sizeof buf, fmt, ap);
    va_end(ap);
    /* Trim trailing newline if the caller included one. */
    size_t n = strlen(buf);
    while (n > 0 && (buf[n - 1] == '\n' || buf[n - 1] == '\r')) buf[--n] = '\0';
    g_printerr("%s%s: %s\n", IDLED_LOG, level, buf);
}

#define log_info(...)  idled_log("info",  __VA_ARGS__)
#define log_warn(...)  idled_log("warn",  __VA_ARGS__)
#define log_err(...)   idled_log("error", __VA_ARGS__)
#define log_debug(...) do { if (g_verbose) idled_log("debug", __VA_ARGS__); } while (0)

/* ------------------------------------------------------------------------- *
 * Settings
 * ------------------------------------------------------------------------- */

/* Plain snapshot of the schema fields the daemon reads. Recomputed on every
 * "changed" signal (debounced) and passed to plan_compute(). */
struct idled_settings {
    char *mode;            /* "off" | "one" | "random" | "playlist" */
    int   hack_idle_delay;
    bool  lock_enabled;
    int   lock_delay;
    bool  lock_on_suspend;
    int   display_off_delay;
};

/* Allocated plan: -1 means "no notification for this role". */
struct idled_plan {
    int  saver;
    int  lock;
    int  dpms;
    bool lock_on_suspend;
};

/* Pure: takes a settings snapshot and returns the derived plan. Used by the
 * dry-run code path too so output matches runtime behavior. */
static struct idled_plan plan_compute(const struct idled_settings *s)
{
    struct idled_plan p = {
        .saver = -1,
        .lock  = -1,
        .dpms  = -1,
        .lock_on_suspend = s->lock_enabled && s->lock_on_suspend,
    };
    bool screensaver_on = strcmp(s->mode, "off") != 0;
    if (screensaver_on) {
        p.saver = s->hack_idle_delay;
        if (s->lock_enabled) p.lock = s->hack_idle_delay + s->lock_delay;
    } else {
        if (s->lock_enabled) p.lock = s->hack_idle_delay;
    }
    if (s->display_off_delay > 0) p.dpms = s->display_off_delay;
    return p;
}

static void settings_clear(struct idled_settings *s)
{
    g_free(s->mode);
    s->mode = NULL;
}

static void settings_load(GSettings *settings, struct idled_settings *out)
{
    settings_clear(out);
    out->mode             = g_settings_get_string(settings, "mode");
    out->hack_idle_delay  = g_settings_get_int(settings, "hack-idle-delay");
    out->lock_enabled     = g_settings_get_boolean(settings, "lock-enabled");
    out->lock_delay       = g_settings_get_int(settings, "lock-delay");
    out->lock_on_suspend  = g_settings_get_boolean(settings, "lock-on-suspend");
    out->display_off_delay= g_settings_get_int(settings, "display-off-delay");
}

/* ------------------------------------------------------------------------- *
 * Forward decls
 * ------------------------------------------------------------------------- */

struct idled_state;

static void plan_apply(struct idled_state *st, const struct idled_settings *s);
static void dpms_set_power(struct idled_state *st, bool on);
static void state_file_update(struct idled_state *st);
static void state_file_remove(struct idled_state *st);
static void state_set(struct idled_state *st, const char *name);
static void request_shutdown(struct idled_state *st, int code);
static void spawn_action_locked(struct idled_state *st);
static void on_child_exited(GPid pid, gint status, gpointer user_data);
static void on_lock_child_exited(GPid pid, gint status, gpointer user_data);
static gboolean logind_inhibit_close_cb(gpointer user_data);

/* ------------------------------------------------------------------------- *
 * State
 * ------------------------------------------------------------------------- */

/* Per-output DPMS binding. The wl_output is owned by the registry; we keep a
 * power control object as long as the manager + output are alive. */
struct output_power {
    struct wl_output *output;
    struct zwlr_output_power_v1 *power;
};

/* Per-role listener trampolines all share this struct as user data, so a
 * single listener struct can dispatch idled/resumed to the right role. */
enum notif_role { ROLE_SAVER, ROLE_LOCK, ROLE_DPMS };

struct role_data {
    struct idled_state *st;
    enum notif_role role;
};

struct idled_state {
    /* CLI / options */
    bool        opt_dry_run;
    bool        opt_verbose;

    /* Configuration */
    GSettings  *gsettings;
    struct idled_settings cur_settings;
    struct idled_plan     cur_plan;
    guint       settings_debounce;     /* g_timeout_add id; 0 = none */

    /* Wayland */
    struct wl_display *w_display;
    GSource           *w_source;
    int                w_fd;
    bool               w_connected;
    struct wl_registry *w_registry;
    struct wl_seat     *w_seat;
    struct ext_idle_notifier_v1 *w_idle;
    /* Tracked globally to bind later when we have a registry handle. */
    uint32_t w_idle_global_name;
    uint32_t w_idle_global_version;
    bool     w_idle_global_seen;
    struct zwlr_output_power_manager_v1 *w_pwr_mgr;
    uint32_t w_pwr_mgr_global_name;
    uint32_t w_pwr_mgr_global_version;
    bool     w_pwr_mgr_global_seen;
    GArray  *w_outputs;       /* struct wl_output * */
    GArray  *w_powers;        /* struct output_power */

    /* Idle notifications, one per enabled role. NULL = not configured. */
    struct ext_idle_notification_v1 *w_saver_notif;
    struct ext_idle_notification_v1 *w_lock_notif;
    struct ext_idle_notification_v1 *w_dpms_notif;

    /* Composite DPMS state (any one notification resumed -> ON). */
    bool saver_idled;
    bool lock_idled;
    bool dpms_idled;
    bool dpms_powered_off; /* did we send off to the outputs? */

    /* Spawned children: pid < 0 means none. We reap via g_child_watch_add. */
    GPid saver_pid;
    GPid stop_pid;
    GPid lock_pid;
    guint lock_watch;

    /* logind */
    GDBusConnection *logind_conn;
    GCancellable   *logind_cancellable;
    char           *logind_session_path;
    int             logind_inhibit_fd_raw;

    /* State file */
    char *state_file_path;
    char *_state_label;   /* owned */

    /* Shutdown coordination. */
    bool _shutdown;
    int  _exit_code;
};

/* ------------------------------------------------------------------------- *
 * State helpers
 * ------------------------------------------------------------------------- */

static const char *state_get(struct idled_state *st)
{
    return st->_state_label ? st->_state_label : "active";
}

static void state_set(struct idled_state *st, const char *name)
{
    g_free(st->_state_label);
    st->_state_label = g_strdup(name);
}

/* ------------------------------------------------------------------------- *
 * Idle notification callbacks
 * ------------------------------------------------------------------------- */

static void on_stop_before_lock_exited(GPid pid, gint status, gpointer user_data)
{
    struct idled_state *st = user_data;
    on_child_exited(pid, status, st);
    spawn_action_locked(st);
}

/* Stop the saver first, then run the lock command once the stop has finished,
 * so the animated overlay never keeps rendering behind the lock surface. */
static void stop_then_lock(struct idled_state *st)
{
    char *argv[] = { "ncz-screensaver", "stop", NULL };
    GError *err = NULL;
    GPid pid = -1;
    if (g_spawn_async(NULL, argv, NULL,
                      G_SPAWN_SEARCH_PATH | G_SPAWN_DO_NOT_REAP_CHILD,
                      NULL, NULL, &pid, &err)) {
        st->stop_pid = pid;
        g_child_watch_add(pid, on_stop_before_lock_exited, st);
        log_debug("lock: stop saver first, pid=%d", (int)pid);
        return;
    }
    log_warn("lock: stop spawn failed: %s", err->message);
    g_clear_error(&err);
    spawn_action_locked(st);
}

static void notif_dispatch_idled(struct idled_state *st, enum notif_role r)
{
    switch (r) {
    case ROLE_SAVER:
        st->saver_idled = true;
        if (st->saver_pid <= 0) {
            char *argv[] = { "ncz-screensaver", "start", "--idle", NULL };
            GError *err = NULL;
            GPid pid = -1;
            if (g_spawn_async(NULL, argv, NULL,
                              G_SPAWN_SEARCH_PATH | G_SPAWN_DO_NOT_REAP_CHILD,
                              NULL, NULL, &pid, &err)) {
                st->saver_pid = pid;
                g_child_watch_add(pid, on_child_exited, st);
                log_debug("saver idled: spawn pid=%d", (int)pid);
            } else {
                log_warn("saver spawn failed: %s", err->message);
                g_clear_error(&err);
            }
        }
        state_set(st, "saver");
        state_file_update(st);
        break;
    case ROLE_LOCK:
        st->lock_idled = true;
        stop_then_lock(st);
        state_set(st, "locked");
        state_file_update(st);
        break;
    case ROLE_DPMS:
        st->dpms_idled = true;
        dpms_set_power(st, false);
        state_set(st, "display-off");
        state_file_update(st);
        break;
    }
}

static void notif_dispatch_resumed(struct idled_state *st, enum notif_role r)
{
    switch (r) {
    case ROLE_SAVER:
        /* The start command detaches and has already exited, so its pid says
         * nothing about whether a saver is running: always ask the launcher to
         * stop (idempotent). */
        st->saver_idled = false;
        {
            char *argv[] = { "ncz-screensaver", "stop", NULL };
            GError *err = NULL;
            GPid pid = -1;
            if (g_spawn_async(NULL, argv, NULL,
                              G_SPAWN_SEARCH_PATH | G_SPAWN_DO_NOT_REAP_CHILD,
                              NULL, NULL, &pid, &err)) {
                g_child_watch_add(pid, on_child_exited, st);
                log_debug("saver resumed: spawn stop pid=%d", (int)pid);
            } else {
                log_warn("saver stop spawn failed: %s", err->message);
                g_clear_error(&err);
            }
        }
        if (!st->lock_idled && !st->dpms_idled) {
            state_set(st, "active");
            state_file_update(st);
        }
        break;
    case ROLE_LOCK:
        st->lock_idled = false;
        if (!st->saver_idled && !st->dpms_idled) {
            state_set(st, "active");
            state_file_update(st);
        }
        break;
    case ROLE_DPMS:
        st->dpms_idled = false;
        /* Any resumed must unconditionally power displays back on. */
        dpms_set_power(st, true);
        if (!st->saver_idled && !st->lock_idled) {
            state_set(st, "active");
            state_file_update(st);
        }
        break;
    }
}

/* Per-role listener trampolines (each notification stores a role_data). */
static void role_trampoline_idled(void *data, struct ext_idle_notification_v1 *n)
{
    (void)n;
    struct role_data *rd = data;
    notif_dispatch_idled(rd->st, rd->role);
}
static void role_trampoline_resumed(void *data, struct ext_idle_notification_v1 *n)
{
    (void)n;
    struct role_data *rd = data;
    notif_dispatch_resumed(rd->st, rd->role);
}
static const struct ext_idle_notification_v1_listener role_listener = {
    .idled   = role_trampoline_idled,
    .resumed = role_trampoline_resumed,
};

/* ------------------------------------------------------------------------- *
 * Spawning + reaping
 * ------------------------------------------------------------------------- */

static void on_child_exited(GPid pid, gint status, gpointer user_data)
{
    struct idled_state *st = user_data;
    log_debug("child pid=%d exited status=%d", (int)pid, status);
    if (pid == st->saver_pid) st->saver_pid = -1;
    if (pid == st->stop_pid)  st->stop_pid  = -1;
    g_spawn_close_pid(pid);
}

static void on_lock_child_exited(GPid pid, gint status, gpointer user_data)
{
    struct idled_state *st = user_data;
    log_debug("lock pid=%d exited status=%d", (int)pid, status);
    if (pid == st->lock_pid) {
        st->lock_pid = -1;
        st->lock_watch = 0;
    }
    g_spawn_close_pid(pid);
}

static char **build_lock_argv(struct idled_state *st, int *argc_out)
{
    (void)st;
    const char *env = g_getenv("NCZ_LOCK_CMD");
    if (env && *env) {
        char **argv = NULL;
        GError *err = NULL;
        if (g_shell_parse_argv(env, NULL, &argv, &err)) {
            if (argc_out) *argc_out = g_strv_length(argv);
            return argv;
        }
        log_warn("NCZ_LOCK_CMD parse failed: %s", err->message);
        g_clear_error(&err);
    }
    static const char *candidates[] = {
        "/usr/local/bin/ncz-lock",
        "/opt/singularity/bin/singularity-lockscreen",
    };
    for (size_t i = 0; i < sizeof candidates / sizeof candidates[0]; i++) {
        if (access(candidates[i], X_OK) == 0) {
            char **argv = g_new0(char *, 2);
            argv[0] = g_strdup(candidates[i]);
            if (argc_out) *argc_out = 1;
            return argv;
        }
    }
    if (argc_out) *argc_out = 0;
    return NULL;
}

/* Try to start the lock command. No-op if a previous lock is still running. */
static void spawn_action_locked(struct idled_state *st)
{
    if (st->lock_pid > 0) {
        log_debug("lock already running pid=%d, skipping", (int)st->lock_pid);
        return;
    }
    int argc = 0;
    char **argv = build_lock_argv(st, &argc);
    if (!argv || argc == 0) {
        log_warn("no lock command available (set NCZ_LOCK_CMD or install ncz-lock)");
        return;
    }
    GError *err = NULL;
    GPid pid = -1;
    if (!g_spawn_async(NULL, argv, NULL,
                       G_SPAWN_SEARCH_PATH | G_SPAWN_DO_NOT_REAP_CHILD,
                       NULL, NULL, &pid, &err)) {
        log_warn("lock spawn failed: %s", err->message);
        g_clear_error(&err);
        g_strfreev(argv);
        return;
    }
    st->lock_pid = pid;
    st->lock_watch = g_child_watch_add(pid, on_lock_child_exited, st);
    log_info("lock spawned pid=%d", (int)pid);
    g_strfreev(argv);
}

/* ------------------------------------------------------------------------- *
 * DPMS via zwlr_output_power_manager_v1
 * ------------------------------------------------------------------------- */

static void output_power_mode(void *data, struct zwlr_output_power_v1 *p, uint32_t mode)
{
    (void)data; (void)p;
    log_debug("output power mode event: mode=%u", mode);
}

static void output_power_failed(void *data, struct zwlr_output_power_v1 *p)
{
    (void)data;
    log_warn("zwlr_output_power_v1 reported failed; destroying");
    zwlr_output_power_v1_destroy(p);
}

static const struct zwlr_output_power_v1_listener power_listener = {
    .mode   = output_power_mode,
    .failed = output_power_failed,
};

static void create_output_power(struct idled_state *st, struct wl_output *out)
{
    if (!st->w_pwr_mgr) return;
    struct zwlr_output_power_v1 *p =
        zwlr_output_power_manager_v1_get_output_power(st->w_pwr_mgr, out);
    if (!p) return;
    struct output_power op = { .output = out, .power = p };
    zwlr_output_power_v1_add_listener(p, &power_listener, st);
    g_array_append_val(st->w_powers, op);
    log_debug("bound output power for wl_output=%p", (void *)out);
}

/* Set power for every output we know about. */
static void dpms_set_power(struct idled_state *st, bool on)
{
    if (!st->w_powers) return;
    struct output_power *arr = (struct output_power *)st->w_powers->data;
    for (guint i = 0; i < st->w_powers->len; i++) {
        if (!arr[i].power) continue;
        enum zwlr_output_power_v1_mode m = on
            ? ZWLR_OUTPUT_POWER_V1_MODE_ON
            : ZWLR_OUTPUT_POWER_V1_MODE_OFF;
        zwlr_output_power_v1_set_mode(arr[i].power, m);
    }
    st->dpms_powered_off = !on;
}

/* ------------------------------------------------------------------------- *
 * Plan application (build/destroy idle notifications)
 * ------------------------------------------------------------------------- */

static void drop_notif(struct ext_idle_notification_v1 **slot)
{
    if (*slot) {
        ext_idle_notification_v1_destroy(*slot);
        *slot = NULL;
    }
}

static void destroy_all_notifs(struct idled_state *st)
{
    drop_notif(&st->w_saver_notif);
    drop_notif(&st->w_lock_notif);
    drop_notif(&st->w_dpms_notif);
    st->saver_idled = st->lock_idled = st->dpms_idled = false;
    /* Rebuilding notifications must not leave outputs powered off. */
    if (st->dpms_powered_off) dpms_set_power(st, true);
}

static struct ext_idle_notification_v1 *
make_notif(struct idled_state *st, enum notif_role role, uint32_t ms)
{
    if (!st->w_idle || !st->w_seat) return NULL;
    struct ext_idle_notification_v1 *n =
        ext_idle_notifier_v1_get_idle_notification(st->w_idle, ms, st->w_seat);
    if (!n) return NULL;
    struct role_data *rd = g_new0(struct role_data, 1);
    rd->st = st;
    rd->role = role;
    ext_idle_notification_v1_add_listener(n, &role_listener, rd);
    return n;
}

static void plan_apply(struct idled_state *st, const struct idled_settings *s)
{
    /* Save the snapshot and recompute the plan (also written to the state
     * file later). */
    /* s may alias st->cur_settings (reload paths) or be a fresh snapshot whose
     * strings are handed over to the state. */
    struct idled_settings snapshot = *s;
    if (s != &st->cur_settings)
        settings_clear(&st->cur_settings);
    st->cur_settings = snapshot;
    st->cur_plan = plan_compute(&st->cur_settings);
    log_debug("plan recomputed: saver=%d lock=%d dpms=%d lock_on_suspend=%d",
              st->cur_plan.saver, st->cur_plan.lock,
              st->cur_plan.dpms, st->cur_plan.lock_on_suspend);
    if (!st->w_idle) return;

    destroy_all_notifs(st);
    if (st->cur_plan.saver > 0)
        st->w_saver_notif = make_notif(st, ROLE_SAVER, (uint32_t)st->cur_plan.saver * 1000u);
    if (st->cur_plan.lock > 0)
        st->w_lock_notif  = make_notif(st, ROLE_LOCK,  (uint32_t)st->cur_plan.lock  * 1000u);
    if (st->cur_plan.dpms > 0)
        st->w_dpms_notif  = make_notif(st, ROLE_DPMS,  (uint32_t)st->cur_plan.dpms  * 1000u);
    state_set(st, "active");
    state_file_update(st);
}

/* ------------------------------------------------------------------------- *
 * State file ($XDG_RUNTIME_DIR/ncz-screensaver/idled.json)
 * ------------------------------------------------------------------------- */

static char *state_dir_path(void)
{
    const char *xdg = g_getenv("XDG_RUNTIME_DIR");
    if (!xdg || !*xdg) xdg = g_get_user_cache_dir();
    return g_build_filename(xdg, "ncz-screensaver", NULL);
}

static char *state_file_path_alloc(void)
{
    char *dir = state_dir_path();
    char *p = g_build_filename(dir, "idled.json", NULL);
    g_free(dir);
    return p;
}

static bool ensure_state_dir(void)
{
    char *dir = state_dir_path();
    if (g_mkdir_with_parents(dir, 0700) != 0) {
        log_warn("mkdir %s: %s", dir, g_strerror(errno));
        g_free(dir);
        return false;
    }
    g_free(dir);
    return true;
}

/* Build the JSON by hand; the shape is small and fixed. We render int-or-null
 * fields using g_strdup_printf and then free them. */
static void state_file_update(struct idled_state *st)
{
    if (!st->state_file_path) return;
    if (!ensure_state_dir()) return;

    /* Build the JSON by hand; the shape is small and fixed. */
    char *saver_str = st->cur_plan.saver > 0
        ? g_strdup_printf("%d", st->cur_plan.saver) : NULL;
    char *lock_str  = st->cur_plan.lock  > 0
        ? g_strdup_printf("%d", st->cur_plan.lock)  : NULL;
    char *dpms_str  = st->cur_plan.dpms  > 0
        ? g_strdup_printf("%d", st->cur_plan.dpms)  : NULL;

    GString *s = g_string_new("{");
    g_string_append_printf(s, "\"pid\":%d,", (int)getpid());
    g_string_append_printf(s, "\"state\":\"%s\",", state_get(st));
    g_string_append(s, "\"plan\":{");
    g_string_append_printf(s, "\"saver\":%s,", saver_str ? saver_str : "null");
    g_string_append_printf(s, "\"lock\":%s,",  lock_str  ? lock_str  : "null");
    g_string_append_printf(s, "\"dpms\":%s,",  dpms_str  ? dpms_str  : "null");
    g_string_append_printf(s, "\"lock_on_suspend\":%s",
                           st->cur_plan.lock_on_suspend ? "true" : "false");
    g_string_append(s, "},");
    g_string_append_printf(s, "\"updated\":%lld", (long long)time(NULL));
    g_string_append(s, "}");

    /* Atomic write: temp file in the same dir + rename. */
    char *tmp = g_strdup_printf("%s.tmp.%d", st->state_file_path, (int)getpid());
    GError *err = NULL;
    if (!g_file_set_contents(tmp, s->str, s->len, &err)) {
        log_warn("state file write failed: %s", err->message);
        g_clear_error(&err);
        goto out;
    }
    if (rename(tmp, st->state_file_path) != 0) {
        log_warn("state file rename %s -> %s: %s", tmp, st->state_file_path, g_strerror(errno));
    }
out:
    g_free(tmp);
    g_string_free(s, TRUE);
    g_free(saver_str);
    g_free(lock_str);
    g_free(dpms_str);
}

static void state_file_remove(struct idled_state *st)
{
    if (!st->state_file_path) return;
    if (unlink(st->state_file_path) != 0 && errno != ENOENT) {
        log_debug("state file unlink failed: %s", g_strerror(errno));
    }
}

/* ------------------------------------------------------------------------- *
 * Wayland registry + binding
 * ------------------------------------------------------------------------- */

static void registry_handle_global(void *data, struct wl_registry *r,
                                   uint32_t name, const char *interface,
                                   uint32_t version);
static void registry_handle_global_remove(void *data, struct wl_registry *r,
                                          uint32_t name);

static const struct wl_registry_listener registry_listener = {
    .global = registry_handle_global,
    .global_remove = registry_handle_global_remove,
};

static void maybe_bind_idle(struct idled_state *st);
static void maybe_bind_pwr_mgr(struct idled_state *st);

static void registry_handle_global(void *data, struct wl_registry *r,
                                   uint32_t name, const char *interface,
                                   uint32_t version)
{
    struct idled_state *st = data;
    if (strcmp(interface, wl_seat_interface.name) == 0 && !st->w_seat) {
        st->w_seat = wl_registry_bind(r, name, &wl_seat_interface, 1);
        log_debug("bound wl_seat (advertised v%u)", version);
    } else if (strcmp(interface, ext_idle_notifier_v1_interface.name) == 0) {
        st->w_idle_global_name    = name;
        st->w_idle_global_version = version;
        st->w_idle_global_seen    = true;
        maybe_bind_idle(st);
    } else if (strcmp(interface, zwlr_output_power_manager_v1_interface.name) == 0) {
        st->w_pwr_mgr_global_name    = name;
        st->w_pwr_mgr_global_version = version;
        st->w_pwr_mgr_global_seen    = true;
        maybe_bind_pwr_mgr(st);
    } else if (strcmp(interface, wl_output_interface.name) == 0) {
        struct wl_output *o = wl_registry_bind(r, name, &wl_output_interface, 1);
        if (o) {
            struct wl_output *boxed = o;
            g_array_append_val(st->w_outputs, boxed);
            create_output_power(st, o);
        }
    }
}

static void registry_handle_global_remove(void *data, struct wl_registry *r, uint32_t name)
{
    (void)r; (void)name; (void)data;
    /* A drop without an event would surface as a dispatch error and exit the
     * daemon. We don't keep a name->proxy table in MVP. */
}

static void maybe_bind_idle(struct idled_state *st)
{
    if (st->w_idle || !st->w_idle_global_seen || !st->w_registry) return;
    uint32_t ver = st->w_idle_global_version;
    /* Honor inhibitors: bind v1 if advertised, else v2. Both versions expose
     * get_idle_notification; we don't need get_input_idle_notification. */
    if (ver > 2) ver = 2;
    if (ver < 1) ver = 1;
    st->w_idle = wl_registry_bind(st->w_registry,
                                  st->w_idle_global_name,
                                  &ext_idle_notifier_v1_interface,
                                  ver);
    if (!st->w_idle) {
        log_err("failed to bind ext_idle_notifier_v1");
        request_shutdown(st, 78);
        return;
    }
    log_debug("bound ext_idle_notifier_v1 v%u", ver);
}

static void maybe_bind_pwr_mgr(struct idled_state *st)
{
    if (st->w_pwr_mgr || !st->w_pwr_mgr_global_seen || !st->w_registry) return;
    uint32_t ver = st->w_pwr_mgr_global_version > 1 ? 1 : st->w_pwr_mgr_global_version;
    st->w_pwr_mgr = wl_registry_bind(st->w_registry,
                                     st->w_pwr_mgr_global_name,
                                     &zwlr_output_power_manager_v1_interface,
                                     ver);
    if (!st->w_pwr_mgr) {
        log_debug("zwlr_output_power_manager_v1 bind failed (non-fatal)");
        return;
    }
    log_debug("bound zwlr_output_power_manager_v1 v%u", ver);
    if (st->w_outputs) {
        struct wl_output **arr = (struct wl_output **)st->w_outputs->data;
        for (guint i = 0; i < st->w_outputs->len; i++) create_output_power(st, arr[i]);
    }
}

/* ------------------------------------------------------------------------- *
 * GSource for wl_display
 * ------------------------------------------------------------------------- */

/* The GSource callback context provides our state; we wire it via
 * g_source_set_callback()'s user_data. */
static gboolean wayland_source_prepare(GSource *src, gint *timeout)
{
    (void)src; (void)timeout;
    return FALSE;  /* we use pollfd -> always polled */
}

static gboolean wayland_source_check(GSource *src)
{
    /* If our pollfd fired, we want to dispatch. The pollfd state was set up
     * in wl_attach_source(). */
    return TRUE;
}

static gboolean wayland_source_dispatch(GSource *src, GSourceFunc cb, gpointer data)
{
    (void)src; (void)cb;
    struct idled_state *st = data;
    if (!st->w_display) return G_SOURCE_REMOVE;
    /* Flush outgoing first so any pending requests reach the compositor. */
    if (wl_display_flush(st->w_display) < 0) {
        log_err("wl_display_flush failed");
        request_shutdown(st, 1);
        return G_SOURCE_REMOVE;
    }
    if (wl_display_prepare_read(st->w_display) == 0) {
        wl_display_read_events(st->w_display);
    }
    if (wl_display_dispatch_pending(st->w_display) < 0) {
        log_err("wl_display_dispatch failed");
        request_shutdown(st, 1);
        return G_SOURCE_REMOVE;
    }
    if (wl_display_get_error(st->w_display) != 0) {
        log_err("wl_display fatal error");
        request_shutdown(st, 1);
        return G_SOURCE_REMOVE;
    }
    return G_SOURCE_CONTINUE;
}

static void wayland_source_finalize(GSource *src)
{
    (void)src;
}

static GSourceFuncs wayland_source_funcs = {
    .prepare  = wayland_source_prepare,
    .check    = wayland_source_check,
    .dispatch = wayland_source_dispatch,
    .finalize = wayland_source_finalize,
};

/* Attach the wayland fd to the GLib main loop. */
static bool wl_attach_source(struct idled_state *st)
{
    st->w_fd = wl_display_get_fd(st->w_display);
    if (st->w_fd < 0) return false;
    GSource *src = g_source_new(&wayland_source_funcs, sizeof(GSource));
    if (!src) return false;
    g_source_set_callback(src, NULL, st, NULL);
    st->w_source = src;
    GPollFD pfd = { .fd = st->w_fd, .events = G_IO_IN | G_IO_HUP | G_IO_ERR, .revents = 0 };
    g_source_add_poll(src, &pfd);
    g_source_attach(src, NULL);
    g_source_unref(src);   /* main loop owns it now */
    return true;
}

/* ------------------------------------------------------------------------- *
 * Top-level Wayland bring-up
 * ------------------------------------------------------------------------- */

static bool wl_handle_init(struct idled_state *st, GError **err)
{
    if (!g_getenv("WAYLAND_DISPLAY") && !g_getenv("WAYLAND_SOCKET")) {
        g_set_error(err, G_IO_ERROR, G_IO_ERROR_NOT_SUPPORTED,
                    "WAYLAND_DISPLAY is not set; this daemon must run inside a Wayland session");
        return false;
    }
    st->w_display = wl_display_connect(NULL);
    if (!st->w_display) {
        g_set_error(err, G_IO_ERROR, G_IO_ERROR_FAILED,
                    "wl_display_connect(NULL) failed");
        return false;
    }
    st->w_powers  = g_array_new(FALSE, FALSE, sizeof(struct output_power));
    st->w_outputs = g_array_new(FALSE, FALSE, sizeof(struct wl_output *));
    st->w_registry = wl_display_get_registry(st->w_display);
    wl_registry_add_listener(st->w_registry, &registry_listener, st);
    if (wl_display_roundtrip(st->w_display) < 0) {
        g_set_error(err, G_IO_ERROR, G_IO_ERROR_FAILED, "wl_display_roundtrip failed");
        return false;
    }
    if (!st->w_seat) {
        g_set_error(err, G_IO_ERROR, G_IO_ERROR_FAILED,
                    "no wl_seat advertised by the compositor");
        return false;
    }
    if (!st->w_idle) {
        g_set_error(err, G_IO_ERROR, G_IO_ERROR_FAILED,
                    "ext_idle_notifier_v1 not advertised by the compositor");
        return false;
    }
    if (!wl_attach_source(st)) {
        g_set_error(err, G_IO_ERROR, G_IO_ERROR_FAILED,
                    "failed to attach wayland fd to the main loop");
        return false;
    }
    st->w_connected = true;
    return true;
}

/* ------------------------------------------------------------------------- *
 * logind (GDBus)
 * ------------------------------------------------------------------------- */

static void logind_signal_cb(GDBusConnection *conn, const char *sender,
                             const char *object_path, const char *interface,
                             const char *signal, GVariant *params,
                             gpointer user_data);
static void logind_acquire_inhibit(struct idled_state *st);
static void logind_get_session(struct idled_state *st);

static void logind_bus_ready(GObject *src, GAsyncResult *res, gpointer user_data)
{
    (void)src;
    struct idled_state *st = user_data;
    GError *err = NULL;
    GDBusConnection *conn = g_bus_get_finish(res, &err);
    if (!conn) {
        log_debug("system bus unavailable: %s (non-fatal)", err->message);
        g_clear_error(&err);
        return;
    }
    st->logind_conn = conn;
    g_dbus_connection_signal_subscribe(
        st->logind_conn, "org.freedesktop.login1",
        "org.freedesktop.login1.Manager",
        NULL, "/org/freedesktop/login1",
        NULL,
        G_DBUS_SIGNAL_FLAGS_NONE,
        logind_signal_cb, st,
        NULL);
    logind_get_session(st);
}

static gboolean logind_inhibit_close_cb(gpointer user_data)
{
    struct idled_state *st = user_data;
    if (st->logind_inhibit_fd_raw >= 0) {
        close(st->logind_inhibit_fd_raw);
        st->logind_inhibit_fd_raw = -1;
        log_debug("released sleep inhibitor");
    }
    return G_SOURCE_REMOVE;
}

static void logind_inhibit_ready(GObject *src, GAsyncResult *res, gpointer user_data)
{
    (void)src;
    struct idled_state *st = user_data;
    GError *err = NULL;
    GUnixFDList *out_fds = NULL;
    GVariant *ret = g_dbus_connection_call_with_unix_fd_list_finish(
        G_DBUS_CONNECTION(src), &out_fds, res, &err);
    if (!ret) {
        log_debug("logind Inhibit failed: %s (non-fatal)", err->message);
        g_clear_error(&err);
        return;
    }
    gint32 handle = -1;
    g_variant_get(ret, "(h)", &handle);
    if (out_fds && handle >= 0) {
        GError *gerr = NULL;
        int fd = g_unix_fd_list_get(out_fds, handle, &gerr);
        if (fd >= 0) {
            st->logind_inhibit_fd_raw = fd;
            log_debug("acquired sleep inhibitor fd=%d", fd);
        } else {
            log_debug("unix fd lookup failed: %s", gerr->message);
            g_clear_error(&gerr);
        }
        g_object_unref(out_fds);
    }
    g_variant_unref(ret);
}

static void logind_acquire_inhibit(struct idled_state *st)
{
    if (!st->logind_conn) return;
    /* Drop any previous one first. */
    if (st->logind_inhibit_fd_raw >= 0) {
        close(st->logind_inhibit_fd_raw);
        st->logind_inhibit_fd_raw = -1;
    }
    GUnixFDList *fds = g_unix_fd_list_new();
    GVariant *args = g_variant_new("(ssss)",
        "sleep", "NCZ screensaver", "Lock the screen before sleep", "delay");
    /* Signature: connection, bus_name, object_path, interface, method, args,
     * reply_type, flags, timeout_msec, fd_list, cancellable, callback, data. */
    g_dbus_connection_call_with_unix_fd_list(
        st->logind_conn,
        "org.freedesktop.login1",
        "/org/freedesktop/login1",
        "org.freedesktop.login1.Manager",
        "Inhibit",
        args,
        G_VARIANT_TYPE("(h)"),
        G_DBUS_CALL_FLAGS_NONE,
        -1,
        fds,
        st->logind_cancellable,
        (GAsyncReadyCallback)logind_inhibit_ready,
        st);
    g_object_unref(fds);
}

static void logind_get_session_ready(GObject *src, GAsyncResult *res, gpointer user_data)
{
    (void)src;
    struct idled_state *st = user_data;
    GError *err = NULL;
    GVariant *ret = g_dbus_connection_call_finish(G_DBUS_CONNECTION(src), res, &err);
    if (!ret) {
        log_debug("logind GetSessionByPID failed: %s", err->message);
        g_clear_error(&err);
        return;
    }
    g_variant_get(ret, "(o)", &st->logind_session_path);
    g_variant_unref(ret);
    if (!st->logind_session_path) return;
    log_debug("logind session=%s", st->logind_session_path);
    g_dbus_connection_signal_subscribe(
        st->logind_conn, "org.freedesktop.login1",
        "org.freedesktop.login1.Session",
        NULL, st->logind_session_path,
        NULL,
        G_DBUS_SIGNAL_FLAGS_NONE,
        logind_signal_cb, st,
        NULL);
    logind_acquire_inhibit(st);
}

static void logind_get_session(struct idled_state *st)
{
    if (!st->logind_conn) return;
    GVariant *args = g_variant_new("(u)", (guint32)getpid());
    g_dbus_connection_call(
        st->logind_conn,
        "org.freedesktop.login1",
        "/org/freedesktop/login1",
        "org.freedesktop.login1.Manager",
        "GetSessionByPID",
        args,
        G_VARIANT_TYPE("(o)"),
        G_DBUS_CALL_FLAGS_NONE,
        -1, st->logind_cancellable,
        (GAsyncReadyCallback)logind_get_session_ready, st);
}

static void logind_signal_cb(GDBusConnection *conn, const char *sender,
                             const char *object_path, const char *interface,
                             const char *signal, GVariant *params,
                             gpointer user_data)
{
    (void)conn; (void)sender; (void)object_path;
    struct idled_state *st = user_data;

    if (g_strcmp0(interface, "org.freedesktop.login1.Manager") == 0 &&
        g_strcmp0(signal, "PrepareForSleep") == 0) {
        gboolean about_to_suspend = FALSE;
        g_variant_get(params, "(b)", &about_to_suspend);
        log_debug("logind PrepareForSleep(%s)", about_to_suspend ? "true" : "false");
        if (about_to_suspend) {
            logind_acquire_inhibit(st);
            if (st->cur_plan.lock_on_suspend) {
                char *argv[] = { "ncz-screensaver", "stop", NULL };
                GError *err = NULL;
                GPid pid = -1;
                if (g_spawn_async(NULL, argv, NULL,
                                  G_SPAWN_SEARCH_PATH | G_SPAWN_DO_NOT_REAP_CHILD,
                                  NULL, NULL, &pid, &err)) {
                    st->stop_pid = pid;
                    g_child_watch_add(pid, on_child_exited, st);
                } else {
                    log_warn("suspend: stop spawn failed: %s", err->message);
                    g_clear_error(&err);
                }
                spawn_action_locked(st);
            }
            /* Close the inhibitor after a 2 s grace so the lock spawns. */
            g_timeout_add(2000, logind_inhibit_close_cb, st);
        } else {
            /* Resume: re-acquire inhibitor for the next round. */
            logind_acquire_inhibit(st);
        }
    } else if (g_strcmp0(interface, "org.freedesktop.login1.Session") == 0 &&
               g_strcmp0(signal, "Lock") == 0) {
        if (st->cur_settings.lock_enabled) {
            char *argv[] = { "ncz-screensaver", "stop", NULL };
            GError *err = NULL;
            GPid pid = -1;
            if (g_spawn_async(NULL, argv, NULL,
                              G_SPAWN_SEARCH_PATH | G_SPAWN_DO_NOT_REAP_CHILD,
                              NULL, NULL, &pid, &err)) {
                st->stop_pid = pid;
                g_child_watch_add(pid, on_child_exited, st);
            } else {
                log_warn("session.Lock: stop spawn failed: %s", err->message);
                g_clear_error(&err);
            }
            spawn_action_locked(st);
        }
    }
}

static void logind_init(struct idled_state *st)
{
    st->logind_cancellable = g_cancellable_new();
    st->logind_inhibit_fd_raw = -1;
    g_bus_get(G_BUS_TYPE_SYSTEM, st->logind_cancellable,
              (GAsyncReadyCallback)logind_bus_ready, st);
}

/* ------------------------------------------------------------------------- *
 * Signals + shutdown
 * ------------------------------------------------------------------------- */

static gboolean on_signal_term(gpointer user_data)
{
    struct idled_state *st = user_data;
    log_info("SIGTERM/INT received, shutting down");
    request_shutdown(st, 0);
    return G_SOURCE_REMOVE;
}

static gboolean on_signal_hup(gpointer user_data)
{
    struct idled_state *st = user_data;
    log_info("SIGHUP received, reloading settings");
    settings_load(st->gsettings, &st->cur_settings);
    plan_apply(st, &st->cur_settings);
    return G_SOURCE_CONTINUE;
}

static gboolean on_settings_changed_debounced(gpointer user_data)
{
    struct idled_state *st = user_data;
    st->settings_debounce = 0;
    settings_load(st->gsettings, &st->cur_settings);
    plan_apply(st, &st->cur_settings);
    return G_SOURCE_REMOVE;
}

static void on_settings_changed(GSettings *settings, const char *key, gpointer user_data)
{
    (void)settings; (void)key;
    struct idled_state *st = user_data;
    /* Debounce 300 ms: the chooser plugin can fire several keys together. */
    if (st->settings_debounce) g_source_remove(st->settings_debounce);
    st->settings_debounce = g_timeout_add(300, on_settings_changed_debounced, st);
}

static GMainLoop *g_loop;

static void request_shutdown(struct idled_state *st, int code)
{
    if (st->_shutdown) return;
    st->_shutdown = TRUE;
    st->_exit_code = code;
    if (g_loop) g_main_loop_quit(g_loop);
}

/* ------------------------------------------------------------------------- *
 * Top-level teardown / state init
 * ------------------------------------------------------------------------- */

static void state_init(struct idled_state *st)
{
    memset(st, 0, sizeof *st);
    st->logind_inhibit_fd_raw = -1;
    st->saver_pid = st->stop_pid = st->lock_pid = -1;
    st->state_file_path = state_file_path_alloc();
    st->_state_label = g_strdup("active");
}

static void state_teardown(struct idled_state *st)
{
    /* Restore outputs to ON, then destroy per-output power objects. */
    if (st->w_powers && st->w_powers->len > 0) {
        struct output_power *arr = (struct output_power *)st->w_powers->data;
        for (guint i = 0; i < st->w_powers->len; i++) {
            if (arr[i].power) {
                zwlr_output_power_v1_set_mode(arr[i].power,
                    ZWLR_OUTPUT_POWER_V1_MODE_ON);
                zwlr_output_power_v1_destroy(arr[i].power);
            }
        }
    }
    if (st->w_idle) {
        if (st->w_saver_notif) ext_idle_notification_v1_destroy(st->w_saver_notif);
        if (st->w_lock_notif)  ext_idle_notification_v1_destroy(st->w_lock_notif);
        if (st->w_dpms_notif)  ext_idle_notification_v1_destroy(st->w_dpms_notif);
        st->w_saver_notif = st->w_lock_notif = st->w_dpms_notif = NULL;
        ext_idle_notifier_v1_destroy(st->w_idle);
        st->w_idle = NULL;
    }
    if (st->w_pwr_mgr) {
        zwlr_output_power_manager_v1_destroy(st->w_pwr_mgr);
        st->w_pwr_mgr = NULL;
    }
    if (st->w_powers) { g_array_free(st->w_powers, TRUE); st->w_powers = NULL; }
    if (st->w_outputs) { g_array_free(st->w_outputs, TRUE); st->w_outputs = NULL; }
    if (st->w_seat)    { wl_seat_destroy(st->w_seat); st->w_seat = NULL; }
    if (st->w_registry){ wl_registry_destroy(st->w_registry); st->w_registry = NULL; }
    if (st->w_display) { wl_display_disconnect(st->w_display); st->w_display = NULL; }
    if (st->logind_inhibit_fd_raw >= 0) close(st->logind_inhibit_fd_raw);
    if (st->logind_cancellable)        g_object_unref(st->logind_cancellable);
    if (st->logind_conn)               g_object_unref(st->logind_conn);
    g_free(st->logind_session_path);
    state_file_remove(st);
    g_free(st->state_file_path);
    g_free(st->_state_label);
    settings_clear(&st->cur_settings);
    if (st->gsettings) g_object_unref(st->gsettings);
    if (st->settings_debounce) g_source_remove(st->settings_debounce);
}

/* ------------------------------------------------------------------------- *
 * CLI / options
 * ------------------------------------------------------------------------- */

static void print_help(void)
{
    g_print(
"Usage: ncz-screensaver-idled [OPTIONS]\n"
"\n"
"Idle timer daemon for NCZ-OS screensaver. Subscribes to ext-idle-notify-v1\n"
"and drives the screensaver, lock and DPMS subsystems per dev.ncz.screensaver\n"
"GSettings.\n"
"\n"
"Options:\n"
"  --dry-run       Print the notification plan as JSON and exit.\n"
"  --verbose       Enable debug logging.\n"
"  --version       Print version and exit.\n"
"  --help          Print this help and exit.\n");
}

static int parse_options(int argc, char **argv, struct idled_state *st)
{
    static const struct option longopts[] = {
        { "dry-run",  no_argument, NULL, 'd' },
        { "verbose",  no_argument, NULL, 'v' },
        { "version",  no_argument, NULL, 'V' },
        { "help",     no_argument, NULL, 'h' },
        { NULL, 0, NULL, 0 },
    };
    int opt;
    while ((opt = getopt_long(argc, argv, "dvVh", longopts, NULL)) != -1) {
        switch (opt) {
        case 'd': st->opt_dry_run = true; break;
        case 'v': st->opt_verbose = true; g_verbose = true; break;
        case 'V': g_print("%s\n", IDLED_VERSION); exit(0);
        case 'h': print_help(); exit(0);
        default:  print_help(); exit(2);
        }
    }
    return optind;
}

/* ------------------------------------------------------------------------- *
 * Dry-run
 * ------------------------------------------------------------------------- */

static int run_dry_run(struct idled_state *st)
{
    if (!st->gsettings) {
        log_err("schema %s not installed", SETTINGS_SCHEMA_ID);
        return 78;
    }
    settings_load(st->gsettings, &st->cur_settings);
    st->cur_plan = plan_compute(&st->cur_settings);
    char *saver_str = st->cur_plan.saver > 0 ? g_strdup_printf("%d", st->cur_plan.saver) : NULL;
    char *lock_str  = st->cur_plan.lock  > 0 ? g_strdup_printf("%d", st->cur_plan.lock)  : NULL;
    char *dpms_str  = st->cur_plan.dpms  > 0 ? g_strdup_printf("%d", st->cur_plan.dpms)  : NULL;
    GString *s = g_string_new("{");
    g_string_append_printf(s, "\"saver\":%s,", saver_str ? saver_str : "null");
    g_string_append_printf(s, "\"lock\":%s,",  lock_str  ? lock_str  : "null");
    g_string_append_printf(s, "\"dpms\":%s,",  dpms_str  ? dpms_str  : "null");
    g_string_append_printf(s, "\"lock_on_suspend\":%s}",
                           st->cur_plan.lock_on_suspend ? "true" : "false");
    g_print("%s\n", s->str);
    g_string_free(s, TRUE);
    g_free(saver_str);
    g_free(lock_str);
    g_free(dpms_str);
    return 0;
}

/* ------------------------------------------------------------------------- *
 * main()
 * ------------------------------------------------------------------------- */

int main(int argc, char **argv)
{
    struct idled_state st;
    state_init(&st);
    parse_options(argc, argv, &st);

    /* Verify the schema is installed. If GSettings can't find it, g_settings_new
     * returns NULL; older glib returns a usable object that fails at first
     * access. We check explicitly so the diagnostic is honest. The default
     * schema source is a GLib-owned singleton and must not be unref'd. */
    GSettingsSchemaSource *source = g_settings_schema_source_get_default();
    GSettingsSchema *schema_check =
        source ? g_settings_schema_source_lookup(source, SETTINGS_SCHEMA_ID, TRUE) : NULL;
    if (!schema_check) {
        log_err("schema %s not installed", SETTINGS_SCHEMA_ID);
        state_teardown(&st);
        return 78;
    }
    g_settings_schema_unref(schema_check);

    st.gsettings = g_settings_new(SETTINGS_SCHEMA_ID);
    if (!st.gsettings) {
        log_err("schema %s not installed", SETTINGS_SCHEMA_ID);
        state_teardown(&st);
        return 78;
    }

    if (st.opt_dry_run) {
        int rc = run_dry_run(&st);
        state_teardown(&st);
        return rc;
    }

    GError *err = NULL;
    if (!wl_handle_init(&st, &err)) {
        log_err("%s", err->message);
        g_clear_error(&err);
        state_teardown(&st);
        return 78;
    }

    g_signal_connect(st.gsettings, "changed", G_CALLBACK(on_settings_changed), &st);

    g_unix_signal_add(SIGTERM, on_signal_term, &st);
    g_unix_signal_add(SIGINT,  on_signal_term, &st);
    g_unix_signal_add(SIGHUP,  on_signal_hup,  &st);

    logind_init(&st);

    struct idled_settings first = {0};
    settings_load(st.gsettings, &first);
    plan_apply(&st, &first); /* takes ownership of the strings in first */
    state_file_update(&st);

    GMainLoop *loop = g_main_loop_new(NULL, FALSE);
    g_loop = loop;
    if (st._shutdown) g_main_loop_quit(loop);
    g_main_loop_run(loop);
    g_loop = NULL;
    g_main_loop_unref(loop);

    int exit_code = st._exit_code;
    state_teardown(&st);
    return exit_code;
}