"""Unit tests for tools/host_test_image.py (the pure PPM helpers).

These tests exercise the parsing and metric helpers in isolation. The full
agent (subprocess orchestration, sudo plumbing, etc.) is tested via
``host-test-agent.py --selftest`` instead; that path needs a Wayland session
and is out of scope here.

Run with ``python3 -m unittest tools.tests.test_host_test_agent`` from the
repo root, or with ``python3 tools/tests/test_host_test_agent.py``.
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

# Make ``tools`` importable when the test is run directly (``python3 test.py``).
_TOOLS = Path(__file__).resolve().parent.parent
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))

import host_test_image as hti


def _make_ppm(width: int, height: int, pixels: list[tuple[int, int, int]]) -> bytes:
    """Build a binary P6 PPM from a flat list of (r, g, b) pixels."""
    out = bytearray()
    out.extend(f"P6\n{width} {height}\n255\n".encode("ascii"))
    for r, g, b in pixels:
        out.append(r & 0xFF)
        out.append(g & 0xFF)
        out.append(b & 0xFF)
    return bytes(out)


class TestParsePPM(unittest.TestCase):
    def test_parses_minimal_frame(self) -> None:
        data = _make_ppm(2, 2, [(255, 0, 0)] * 4)
        w, h, rgb = hti.parse_ppm(data)
        self.assertEqual((w, h), (2, 2))
        self.assertEqual(len(rgb), 12)
        self.assertEqual(rgb, b"\xff\x00\x00" * 4)

    def test_tolerates_comment_line(self) -> None:
        # Real-world PPMs from grim/conversion tools often have a comment.
        data = (
            b"P6\n# generated by the test harness\n2 1\n255\n"
            + b"\x10\x20\x30\x40\x50\x60"
        )
        w, h, rgb = hti.parse_ppm(data)
        self.assertEqual((w, h), (2, 1))
        self.assertEqual(rgb, b"\x10\x20\x30\x40\x50\x60")

    def test_rejects_p5_ascii(self) -> None:
        with self.assertRaises(hti.PPMError):
            hti.parse_ppm(b"P5\n1 1\n255\n\xff")

    def test_rejects_truncated_payload(self) -> None:
        with self.assertRaises(hti.PPMError):
            hti.parse_ppm(_make_ppm(4, 4, [(0, 0, 0)] * 4)[:20])

    def test_rejects_non_255_maxval(self) -> None:
        with self.assertRaises(hti.PPMError):
            hti.parse_ppm(b"P6\n1 1\n511\n\xff\xff\xff")

    def test_rejects_missing_dimensions(self) -> None:
        with self.assertRaises(hti.PPMError):
            hti.parse_ppm(b"P6\n\n255\n\x00\x00\x00")


class TestCoverageFraction(unittest.TestCase):
    def test_fully_black(self) -> None:
        self.assertEqual(hti.coverage_fraction(b"\x00\x00\x00" * 16), 0.0)

    def test_fully_white(self) -> None:
        self.assertEqual(hti.coverage_fraction(b"\xff\xff\xff" * 16), 1.0)

    def test_half_bright(self) -> None:
        buf = b"\xff\xff\xff" * 8 + b"\x00\x00\x00" * 8
        self.assertEqual(hti.coverage_fraction(buf), 0.5)

    def test_threshold_inclusive_upper(self) -> None:
        # Bright threshold is strict greater-than: 16 == threshold, 17 passes.
        buf = b"\x11\x11\x11" * 4
        self.assertEqual(hti.coverage_fraction(buf, threshold=16), 1.0)
        buf = b"\x10\x10\x10" * 4
        self.assertEqual(hti.coverage_fraction(buf, threshold=16), 0.0)

    def test_empty_buffer(self) -> None:
        self.assertEqual(hti.coverage_fraction(b""), 0.0)

    def test_rejects_misaligned_length(self) -> None:
        with self.assertRaises(hti.PPMError):
            hti.coverage_fraction(b"\xff\xff")  # 2 bytes, not a multiple of 3


class TestFrameDiffFraction(unittest.TestCase):
    def test_identical_frames(self) -> None:
        a = b"\x80\x80\x80" * 4
        b_same = b"\x80\x80\x80" * 4
        self.assertEqual(hti.frame_diff_fraction(a, b_same), 0.0)

    def test_small_jitter_below_threshold(self) -> None:
        a = b"\x80\x80\x80" * 4
        # Diff of 10 on a single channel is below default threshold (12).
        b = bytearray(a)
        b[0] = 0x80 + 10  # first pixel's R goes 128 -> 138, diff = 10
        self.assertEqual(hti.frame_diff_fraction(a, bytes(b)), 0.0)

    def test_large_change_counted(self) -> None:
        a = b"\x00\x00\x00" * 8
        b = b"\xff\xff\xff" * 8
        self.assertEqual(hti.frame_diff_fraction(a, b), 1.0)

    def test_partial_change(self) -> None:
        a = b"\x00\x00\x00" * 4
        b = b"\xff\x00\x00" + b"\x00\x00\x00" * 3
        # Only the first pixel differs, and only its R channel. With the
        # default threshold of 12, |0 - 255| > 12 so it counts.
        self.assertEqual(hti.frame_diff_fraction(a, b), 0.25)

    def test_rejects_length_mismatch(self) -> None:
        with self.assertRaises(hti.PPMError):
            hti.frame_diff_fraction(b"\x00\x00\x00", b"\x00\x00")

    def test_empty(self) -> None:
        self.assertEqual(hti.frame_diff_fraction(b"", b""), 0.0)


class TestMeanBrightnessAndChromaticity(unittest.TestCase):
    def test_no_bright_pixels(self) -> None:
        r, g, b, n = hti.mean_brightness_of_bright_pixels(b"\x00\x00\x00" * 4)
        self.assertEqual((r, g, b, n), (0.0, 0.0, 0.0, 0))

    def test_uniform_red(self) -> None:
        # 4 red pixels at (255, 0, 0): all pass threshold, mean R = 255.
        r, g, b, n = hti.mean_brightness_of_bright_pixels(b"\xff\x00\x00" * 4)
        self.assertEqual(n, 4)
        self.assertEqual((r, g, b), (255.0, 0.0, 0.0))

    def test_uniform_blue(self) -> None:
        r, g, b, n = hti.mean_brightness_of_bright_pixels(b"\x00\x00\xff" * 4)
        self.assertEqual(n, 4)
        # Blue is dropped from the chromaticity vector, so distance to red
        # is a real measurement of "looks different".
        self.assertEqual((r, g, b), (0.0, 0.0, 255.0))

    def test_chromaticity_red_vs_blue(self) -> None:
        red = (255.0, 0.0, 0.0)
        blue = (0.0, 0.0, 255.0)
        d = hti.chromaticity_distance(red, blue)
        # Red chromaticity = (1.0, 0.0); blue = (0.0, 0.0); distance = 1.0.
        self.assertAlmostEqual(d, 1.0, places=6)

    def test_chromaticity_identical(self) -> None:
        a = (120.0, 80.0, 40.0)
        b = (240.0, 160.0, 80.0)
        # Same hue, different brightness: chromaticity distance == 0.
        self.assertEqual(hti.chromaticity_distance(a, b), 0.0)

    def test_chromaticity_black_vs_anything(self) -> None:
        # Black frames collapse to the same point (0, 0); distance == 0.
        self.assertEqual(hti.chromaticity_distance((0, 0, 0), (100, 50, 25)), 0.0)

    def test_brightness_ratio(self) -> None:
        self.assertAlmostEqual(hti.brightness_ratio(100.0, 200.0), 2.0)
        self.assertAlmostEqual(hti.brightness_ratio(200.0, 100.0), 2.0)
        self.assertEqual(hti.brightness_ratio(50.0, 50.0), 1.0)

    def test_brightness_ratio_with_zero(self) -> None:
        # If either operand is zero the ratio is treated as 1 (the caller
        # should already have excluded the all-black case).
        self.assertEqual(hti.brightness_ratio(0.0, 100.0), 1.0)
        self.assertEqual(hti.brightness_ratio(100.0, 0.0), 1.0)


class TestPerformance(unittest.TestCase):
    """Soft timing assertions: 480x270 PPM (the default grim scale) must
    stay well under one second for the metric helpers. These tests are not
    tight: a 5x margin catches accidental quadratic regressions without
    flaking on a slow CI runner."""

    def _frame(self, seed: int) -> bytes:
        # Deterministic synthetic frame: 480x270 of pseudo-random RGB.
        n = 480 * 270 * 3
        out = bytearray(n)
        v = seed & 0xFF
        for i in range(n):
            v = (v * 1103515245 + 12345) & 0x7FFFFFFF
            out[i] = (v >> 16) & 0xFF
        return bytes(out)

    def test_coverage_under_budget(self) -> None:
        import time

        buf = self._frame(1)
        start = time.monotonic()
        for _ in range(5):
            hti.coverage_fraction(buf)
        elapsed = time.monotonic() - start
        self.assertLess(elapsed, 5.0, f"coverage took {elapsed:.2f}s, budget 5s")

    def test_diff_under_budget(self) -> None:
        import time

        a = self._frame(2)
        b = self._frame(3)
        start = time.monotonic()
        for _ in range(5):
            hti.frame_diff_fraction(a, b)
        elapsed = time.monotonic() - start
        self.assertLess(elapsed, 5.0, f"diff took {elapsed:.2f}s, budget 5s")


if __name__ == "__main__":
    unittest.main()


class PpmWhitespacePixelTest(unittest.TestCase):
    """Pixel bytes equal to ASCII whitespace right after the header are data."""

    def test_leading_whitespace_valued_pixels(self):
        import host_test_image as hti

        data = b"P6\n2 1\n255\n" + bytes([32, 9, 10, 0, 0, 0])
        w, h, rgb = hti.parse_ppm(data)
        self.assertEqual((w, h, len(rgb)), (2, 1, 6))
        self.assertEqual(rgb[0], 32)
