#!/usr/bin/env python3
"""Convert PubChem 3D SDF records into a compact C header for apothecary.

PubChem (NIH/NCBI) is a US government work and therefore public domain: no
attribution burden and no share-alike, which is why it is the sole source.
ChEMBL (CC BY-SA) and ChemSpider (API terms) are deliberately NOT used -- a
share-alike obligation would propagate into the shipped OS image.

The screensaver performs ZERO network I/O at runtime, so every structure is
baked in here at build time.
"""

import glob
import json
import os
import sys

# Covalent radii (angstrom) and CPK colours. Both are published factual
# reference data, not derived from any implementation.
ELEMENTS = {
    "H": (0.31, (1.00, 1.00, 1.00)),
    "C": (0.76, (0.25, 0.25, 0.28)),
    "N": (0.71, (0.19, 0.31, 0.97)),
    "O": (0.66, (1.00, 0.19, 0.16)),
    "P": (1.07, (1.00, 0.50, 0.00)),
    "S": (1.05, (1.00, 0.85, 0.19)),
    "Cl": (1.02, (0.12, 0.94, 0.12)),
    "F": (0.57, (0.56, 0.88, 0.31)),
    "Br": (1.20, (0.65, 0.16, 0.16)),
    "I": (1.39, (0.58, 0.00, 0.58)),
    "Fe": (1.32, (0.88, 0.40, 0.20)),
    "Mg": (1.41, (0.54, 1.00, 0.00)),
    "Na": (1.66, (0.67, 0.36, 0.95)),
    "Zn": (1.22, (0.49, 0.50, 0.69)),
    "Co": (1.26, (0.94, 0.56, 0.63)),
}


def parse_sdf(path):
    lines = open(path, errors="ignore").read().splitlines()
    if len(lines) < 5:
        return None
    try:
        na = int(lines[3][0:3])
        nb = int(lines[3][3:6])
    except Exception:
        return None
    if na < 2 or na > 200:
        return None
    atoms = []
    for i in range(4, 4 + na):
        p = lines[i].split()
        if len(p) < 4:
            return None
        el = p[3]
        if el not in ELEMENTS:
            return None
        atoms.append((float(p[0]), float(p[1]), float(p[2]), el))
    bonds = []
    for i in range(4 + na, 4 + na + nb):
        l = lines[i]
        try:
            a = int(l[0:3])
            b = int(l[3:6])
            o = int(l[6:9])
        except Exception:
            continue
        if 1 <= a <= na and 1 <= b <= na:
            bonds.append((a - 1, b - 1, max(1, min(3, o))))
    # centre on the centroid so the renderer never has to
    cx = sum(a[0] for a in atoms) / na
    cy = sum(a[1] for a in atoms) / na
    cz = sum(a[2] for a in atoms) / na
    atoms = [(a[0] - cx, a[1] - cy, a[2] - cz, a[3]) for a in atoms]
    radius = max((x * x + y * y + z * z) ** 0.5 for x, y, z, _ in atoms) or 1.0
    return atoms, bonds, radius


THEMES = json.load(open(sys.argv[2])) if len(sys.argv) > 2 else {}


def main():
    src = sys.argv[1]
    recs = []
    for f in sorted(glob.glob(os.path.join(src, "*.sdf"))):
        name = os.path.basename(f)[:-4]
        r = parse_sdf(f)
        if not r:
            print(
                f"  skip {name} (unparseable or unsupported element)", file=sys.stderr
            )
            continue
        recs.append((name, *r))
    els = sorted({a[3] for _, atoms, _, _ in recs for a in atoms})
    out = []
    out.append("/* Generated by tools/apothecary-sdf-to-header.py -- do not edit. */")
    out.append("/* Structures: PubChem (NIH/NCBI), public domain. */")
    out.append("#ifndef APOTHECARY_DATA_H")
    out.append("#define APOTHECARY_DATA_H")
    out.append("")
    out.append("typedef struct { float x, y, z; unsigned char el; } apo_atom;")
    out.append("typedef struct { unsigned short a, b; unsigned char order; } apo_bond;")
    out.append("typedef struct { const char *name; const apo_atom *atoms; int n_atoms;")
    out.append("                 const apo_bond *bonds; int n_bonds; float radius;")
    out.append("                 unsigned char theme; } apo_molecule;")
    out.append("")
    out.append("/* element table: covalent radius (angstrom) + CPK colour */")
    out.append(
        "typedef struct { const char *sym; float radius; float r, g, b; } apo_element;"
    )
    out.append("static const apo_element APO_ELEMENTS[] = {")
    for e in els:
        rad, (r, g, b) = ELEMENTS[e]
        out.append(f'    {{ "{e}", {rad:.2f}f, {r:.2f}f, {g:.2f}f, {b:.2f}f }},')
    out.append("};")
    out.append(f"#define APO_N_ELEMENTS {len(els)}")
    out.append("")
    idx = {e: i for i, e in enumerate(els)}
    for name, atoms, bonds, rad in recs:
        c = name.replace("-", "_")
        out.append(f"static const apo_atom apo_{c}_a[] = {{")
        for x, y, z, e in atoms:
            out.append(f"    {{ {x:.3f}f, {y:.3f}f, {z:.3f}f, {idx[e]} }},")
        out.append("};")
        if bonds:
            out.append(f"static const apo_bond apo_{c}_b[] = {{")
            for a, b, o in bonds:
                out.append(f"    {{ {a}, {b}, {o} }},")
            out.append("};")
    out.append("")
    out.append("static const apo_molecule APO_MOLECULES[] = {")
    for name, atoms, bonds, rad in recs:
        c = name.replace("-", "_")
        bref = f"apo_{c}_b" if bonds else "0"
        th = THEMES.get(name, 0)
        out.append(
            f'    {{ "{name}", apo_{c}_a, {len(atoms)}, {bref}, {len(bonds)}, {rad:.3f}f, {th} }},'
        )
    out.append("};")
    out.append(f"#define APO_N_MOLECULES {len(recs)}")
    out.append("")
    out.append("#endif")
    sys.stdout.write("\n".join(out) + "\n")
    print(
        f"emitted {len(recs)} molecules, {sum(len(a) for _, a, _, _ in recs)} atoms, "
        f"{len(els)} elements",
        file=sys.stderr,
    )


main()
