#!/usr/bin/env python3
"""png_to_h.py — convert a PNG into a header file with the bytes
embedded as a `static const unsigned char <name>_png[]` C array.

Cheap, no external deps beyond Python stdlib (zlib + struct).
The wrapped byte stream is the original PNG byte stream (NOT a
decoded bitmap), matching how xscreensaver's `hacks/images/gen/*_png.h`
files are generated by `mkparr` upstream.

Usage:
    png_to_h.py <input.png> <name> <output.h>

Produces:
    static const unsigned char <name>_png[] = { byte, byte, byte, ... };

The header is wrapped in the standard xscreensaver `__extension__`
pragma so older GCCs accept the implicit `static const unsigned char[]`
declaration in C90 pedantic mode.

This file intentionally stays tiny — it is invoked from a meson
`custom_target()` in `meson.build` for any hack that needs a PNG
embedded at build time.
"""
import sys
import os

def main(argv):
    if len(argv) != 4:
        print("usage: png_to_h.py <input.png> <name> <output.h>", file=sys.stderr)
        return 2
    in_path, name, out_path = argv[1], argv[2], argv[3]
    if not os.path.isfile(in_path):
        print("missing input: %s" % in_path, file=sys.stderr)
        return 2
    with open(in_path, "rb") as f:
        data = f.read()
    out_dir = os.path.dirname(os.path.abspath(out_path))
    os.makedirs(out_dir, exist_ok=True)
    lines = []
    lines.append("/* Auto-generated by tools/png_to_h.py — do not edit. */")
    lines.append("#ifdef __GNUC__")
    lines.append("__extension__")
    lines.append("#endif")
    lines.append("static const unsigned char %s_png[] = {" % name)
    # 12 bytes per row, escaped ASCII for readability. Each row stays
    # under the 80-column limit and parses unambiguously as integer
    # literals.
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        bytes_str = ",".join("0x%02x" % b for b in chunk)
        lines.append("    %s," % bytes_str)
    lines.append("};")
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
