/* GLES3 port of Adriwin06/black-hole's Schwarzschild Binet integrator. */
#define _POSIX_C_SOURCE 200809L
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
#include <GLES3/gl32.h>
#include "gles3_compat.h"
#include "xscreensaver_compat.h"
typedef struct { GLuint program,vbo; GLint time,resolution,seed,radius,temperature,density,rotation,inclination,orbit_rate,jet,star_density,camera_mode,palette; double started; float v[11]; } State;
static double now(void){struct timespec t;clock_gettime(CLOCK_MONOTONIC,&t);return t.tv_sec+t.tv_nsec*1e-9;}
static uint32_t seed(void){uint32_t s=0;int f=open("/dev/urandom",O_RDONLY|O_CLOEXEC);if(f>=0){ssize_t n=read(f,&s,4);close(f);if(n==4)return s;}struct timespec t;clock_gettime(CLOCK_REALTIME,&t);return t.tv_nsec^t.tv_sec^getpid();}
static float rnd(uint32_t*s,float a,float b){*s^=*s<<13;*s^=*s>>17;*s^=*s<<5;return a+(b-a)*(float)(*s&0xffffffu)/16777215.f;}
static char*load(void){const char*p[]={"vendor/blackhole/blackhole.frag","../vendor/blackhole/blackhole.frag","../../vendor/blackhole/blackhole.frag","/usr/share/ncz-screensavers/shaders/blackhole.frag"};FILE*f=0;const char*u=0;for(unsigned i=0;i<4;i++)if((f=fopen(p[i],"rb"))){u=p[i];break;}if(!f){fprintf(stderr,"blackhole: cannot locate shader\n");return 0;}fseek(f,0,SEEK_END);long n=ftell(f);rewind(f);char*b=malloc(n+1);if(!b||fread(b,1,n,f)!=(size_t)n){free(b);fclose(f);return 0;}fclose(f);b[n]=0;fprintf(stderr,"[diag] blackhole shader=%s\n",u);return b;}
static GLuint comp(GLenum t,const char*x){GLuint s=glCreateShader(t);glShaderSource(s,1,&x,0);glCompileShader(s);GLint ok=0;glGetShaderiv(s,GL_COMPILE_STATUS,&ok);if(!ok){char l[8192];glGetShaderInfoLog(s,sizeof l,0,l);fprintf(stderr,"blackhole compile: %s\n",l);glDeleteShader(s);return 0;}return s;}
static void init_blackhole(ModeInfo*m){static const char*vs="#version 300 es\nlayout(location=0) in vec2 p;void main(){gl_Position=vec4(p,0,1);}\n";State*s=calloc(1,sizeof*s);if(!s){ncz_harness_die(1);return;}m->data=s;char*x=load();if(!x){ncz_harness_die(1);return;}GLuint v=comp(GL_VERTEX_SHADER,vs),f=comp(GL_FRAGMENT_SHADER,x);free(x);if(!v||!f){ncz_harness_die(1);return;}s->program=glCreateProgram();glAttachShader(s->program,v);glAttachShader(s->program,f);glLinkProgram(s->program);glDeleteShader(v);glDeleteShader(f);GLint ok=0;glGetProgramiv(s->program,GL_LINK_STATUS,&ok);if(!ok){char l[8192];glGetProgramInfoLog(s->program,sizeof l,0,l);fprintf(stderr,"blackhole link: %s\n",l);ncz_harness_die(1);return;}const float q[]={-1,-1,1,-1,-1,1,-1,1,1,-1,1,1};glGenBuffers(1,&s->vbo);glBindBuffer(GL_ARRAY_BUFFER,s->vbo);glBufferData(GL_ARRAY_BUFFER,sizeof q,q,GL_STATIC_DRAW);glBindBuffer(GL_ARRAY_BUFFER,0);
#define L(n) s->n=glGetUniformLocation(s->program,"u_"#n)
L(time);L(resolution);L(seed);L(radius);L(temperature);L(density);L(rotation);L(inclination);L(orbit_rate);L(jet);L(star_density);L(camera_mode);L(palette);
#undef L
uint32_t z=seed();s->v[0]=(float)z;s->v[1]=rnd(&z,.82,1.15);s->v[2]=rnd(&z,.45,1);s->v[3]=rnd(&z,.72,1.3);s->v[4]=(rnd(&z,0,1)<.5?-1:1)*rnd(&z,.65,1.35);s->v[5]=rnd(&z,.18,.48);s->v[6]=rnd(&z,.175,.235);s->v[7]=rnd(&z,0,1)<.42?rnd(&z,.25,.75):0;s->v[8]=rnd(&z,.55,1.25);s->v[9]=(float)((z>>8)%3);s->v[10]=(float)((z>>16)%5);s->started=now();fprintf(stderr,"[diag] blackhole seed=%.0f radius=%.3f temp=%.3f density=%.3f rotation=%.3f inclination=%.3f flyby=%d camera_rate=%.4f palette=%d jet=%.3f stars=%.3f GL=%s\n",s->v[0],s->v[1],s->v[2],s->v[3],s->v[4],s->v[5],(int)s->v[9],s->v[6],(int)s->v[10],s->v[7],s->v[8],glGetString(GL_VERSION));}
static void draw_blackhole(ModeInfo*m){State*s=m->data;if(!s||!s->program)return;int w=m->xgwa.width,h=m->xgwa.height;if(w<1)w=1;if(h<1)h=1;glViewport(0,0,w,h);glClear(GL_COLOR_BUFFER_BIT);glUseProgram(s->program);glUniform1f(s->time,now()-s->started);glUniform2f(s->resolution,w,h);glUniform1f(s->seed,s->v[0]);glUniform1f(s->radius,s->v[1]);glUniform1f(s->temperature,s->v[2]);glUniform1f(s->density,s->v[3]);glUniform1f(s->rotation,s->v[4]);glUniform1f(s->inclination,s->v[5]);glUniform1f(s->orbit_rate,s->v[6]);glUniform1f(s->jet,s->v[7]);glUniform1f(s->star_density,s->v[8]);glUniform1f(s->camera_mode,s->v[9]);glUniform1f(s->palette,s->v[10]);glBindBuffer(GL_ARRAY_BUFFER,s->vbo);glEnableVertexAttribArray(0);glVertexAttribPointer(0,2,GL_FLOAT,GL_FALSE,0,0);glDisable(GL_DEPTH_TEST);ncz_gles3_draw_arrays(GL_TRIANGLES,0,6);glDisableVertexAttribArray(0);glBindBuffer(GL_ARRAY_BUFFER,0);glUseProgram(0);static int once;if(!once++){unsigned char px[16]={0};glReadPixels(w/2,h/2,1,1,GL_RGBA,GL_UNSIGNED_BYTE,px);glReadPixels(w/8,h/8,1,1,GL_RGBA,GL_UNSIGNED_BYTE,px+4);glReadPixels(7*w/8,h/8,1,1,GL_RGBA,GL_UNSIGNED_BYTE,px+8);glReadPixels(w/8,7*h/8,1,1,GL_RGBA,GL_UNSIGNED_BYTE,px+12);GLenum e=glGetError();fprintf(stderr,"[diag] blackhole first draw gl_error=0x%x samples=%u,%u,%u;%u,%u,%u;%u,%u,%u;%u,%u,%u uniforms=time:%d resolution:%d seed:%d camera:%d palette:%d\n",e,px[0],px[1],px[2],px[4],px[5],px[6],px[8],px[9],px[10],px[12],px[13],px[14],s->time,s->resolution,s->seed,s->camera_mode,s->palette);}}
static void free_blackhole(ModeInfo*m){State*s=m->data;if(!s)return;if(s->vbo)glDeleteBuffers(1,&s->vbo);if(s->program)glDeleteProgram(s->program);free(s);m->data=0;}static void reshape_blackhole(ModeInfo*m,int w,int h){(void)m;(void)w;(void)h;}static Bool blackhole_handle_event(ModeInfo*m,XEvent*e){(void)m;(void)e;return False;}static void release_blackhole(ModeInfo*m){(void)m;}static ModeSpecOpt blackhole_opts={0,NULL,0,NULL,NULL};
struct xscreensaver_function_table blackhole_xscreensaver_function_table={.name="blackhole",.class_="BlackHole",.init_cb=init_blackhole,.draw_cb=draw_blackhole,.reshape_cb=reshape_blackhole,.event_cb=blackhole_handle_event,.free_cb=free_blackhole,.release_cb=release_blackhole,.opts=&blackhole_opts,.defaults_str=DEFAULTS};
