/*
 * wl-screenhack.c — native Wayland/EGL/GLES2 screensaver shell.
 *
 * Round 1 foundation: wlr-layer-shell surface + EGL window + GLES2 context,
 * driven by wl_surface frame callbacks, rendering a smoothly rotating
 * hue-cycling equilateral triangle as a placeholder "test effect".
 *
 * Designed so the effect API (init/reshape/draw/free, struct effect) can be
 * factored out into its own translation unit in later rounds when we begin
 * porting xscreensaver's GPL hacks. This shell will then dispatch to a
 * selected effect based on e.g. -e <name>.
 *
 * NO X11 / GLX / Xlib / Xwayland anywhere. Pure Wayland + EGL + GLES2.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdbool.h>
#include <signal.h>
#include <math.h>
#include <time.h>
#include <errno.h>
#include <poll.h>

#include <wayland-client.h>
#include <wayland-egl.h>

#include <EGL/egl.h>
#include <EGL/eglplatform.h>
#include <GLES2/gl2.h>

/*
 * Generated by wayland-scanner from protocols/wayland.xml,
 * protocols/xdg-shell.xml, protocols/wlr-layer-shell-unstable-v1.xml
 * via custom_targets in meson.build.
 */
#include "wayland-client-protocol.h"
#include "xdg-shell-client-protocol.h"
#include "wlr-layer-shell-unstable-v1-client-protocol.h"

/* -------------------------------------------------------------------------- */
/* Macros                                                                     */
/* -------------------------------------------------------------------------- */

/* Checked call: on failure print a clear diagnostic to stderr and exit(1).
 * We deliberately use a macro so the call site reads cleanly.
 *
 * The macro evaluates `call` exactly once and `expected` may be any
 * expression of an integer type comparable to `call`. We treat EGL_FALSE
 * (==0) and NULL as failure for the relevant types, and any return value
 * != `expected` for the rest. The `fmt`/`...` arguments are appended to
 * a base message so callers can add context.
 */
#define DIE(call, expected, fmt, ...)                                          \
    do {                                                                       \
        long long _ret = (long long)(call);                                    \
        long long _exp = (long long)(expected);                                \
        if (_ret != _exp) {                                                    \
            fprintf(stderr,                                                   \
                    "wl-screenhack: %s failed at %s:%d: " fmt "\n",            \
                    #call, __FILE__, __LINE__, ##__VA_ARGS__);                 \
            exit(1);                                                           \
        }                                                                      \
    } while (0)

/* -------------------------------------------------------------------------- */
/* Effect API                                                                 */
/* -------------------------------------------------------------------------- */

/*
 * The effect API. Future rounds will define one struct effect per ported
 * xscreensaver hack; this file ships a single static one as a placeholder.
 *
 * All callbacks receive the effect's `user` (caller-owned) and may freely
 * read/write it. draw() must NOT block; reshape() is called when the
 * window size changes; free() releases all per-effect GL resources.
 */
struct effect {
    const char *name;
    int  (*init)(struct effect *e);
    void (*reshape)(struct effect *e, int width, int height);
    void (*draw)(struct effect *e, double now_seconds);
    void (*free)(struct effect *e);
    void *user;
};

/* -------------------------------------------------------------------------- */
/* Test effect: rotating hue-cycling equilateral triangle                     */
/* -------------------------------------------------------------------------- */

struct triangle_state {
    GLuint program;
    GLuint vbo;
    GLint  u_angle_loc;
    GLint  u_time_loc;
};

/*
 * Equilateral triangle in clip space, centered at origin, circumradius r=0.8.
 * Vertices at angles 90°, 210°, 330° from +Y — top, lower-left, lower-right.
 * Each vertex is a 2-component (x, y) vec2 to match `attribute vec2 a_pos`.
 *
 *   top       ( 0.0,             0.8)              = ( r·cos 90°,  r·sin 90°)
 *   lower-L   (-0.6928,         -0.4)              = ( r·cos210°,  r·sin210°)
 *   lower-R   ( 0.6928,         -0.4)              = ( r·cos330°,  r·sin330°)
 *
 * With r = 0.8: r·√3/2 ≈ 0.6928, and r/2 = 0.4.
 */
static const GLfloat k_triangle_verts[6] = {
     0.0f,    0.8f,
    -0.6928f, -0.4f,
     0.6928f, -0.4f,
};

static const char *k_vertex_shader_src =
    "attribute vec2 a_pos;\n"
    "uniform float u_angle;\n"
    "void main() {\n"
    "    float c = cos(u_angle);\n"
    "    float s = sin(u_angle);\n"
    "    mat2 R = mat2(c, -s, s, c);\n"
    "    gl_Position = vec4(R * a_pos, 0.0, 1.0);\n"
    "}\n";

/*
 * Convert HSV (h in [0,1]) to RGB. Hue cycles through full rainbow at
 * 1 cycle / 12 s, so the triangle's color smoothly flows.
 */
static const char *k_fragment_shader_src =
    "precision mediump float;\n"
    "uniform float u_time;\n"
    "\n"
    "vec3 hsv2rgb(vec3 c) {\n"
    "    vec4 K = vec4(1.0, 2.0/3.0, 1.0/3.0, 3.0);\n"
    "    vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);\n"
    "    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    float h = fract(u_time / 12.0);\n"
    "    vec3 rgb = hsv2rgb(vec3(h, 0.85, 1.0));\n"
    "    gl_FragColor = vec4(rgb, 1.0);\n"
    "}\n";

static GLuint compile_shader(GLenum type, const char *src, const char *label) {
    GLuint s = glCreateShader(type);
    DIE(s, (GLuint)0, "glCreateShader(%s) returned 0", label);
    glShaderSource(s, 1, &src, NULL);
    glCompileShader(s);
    GLint ok = GL_FALSE;
    glGetShaderiv(s, GL_COMPILE_STATUS, &ok);
    if (!ok) {
        char log[512];
        GLsizei n = 0;
        glGetShaderInfoLog(s, sizeof(log), &n, log);
        fprintf(stderr,
                "wl-screenhack: %s shader compile failed (%" PRIu32 " bytes): %.*s\n",
                label, (uint32_t)n, (int)n, log);
        glDeleteShader(s);
        exit(1);
    }
    return s;
}

static int triangle_init(struct effect *e) {
    struct triangle_state *st = e->user;

    GLuint vs = compile_shader(GL_VERTEX_SHADER,   k_vertex_shader_src,   "vertex");
    GLuint fs = compile_shader(GL_FRAGMENT_SHADER, k_fragment_shader_src, "fragment");

    st->program = glCreateProgram();
    DIE(st->program, (GLuint)0, "glCreateProgram returned 0");
    glAttachShader(st->program, vs);
    glAttachShader(st->program, fs);
    glBindAttribLocation(st->program, 0, "a_pos");
    glLinkProgram(st->program);

    /* Shaders may be deleted after link; they're retained by the program. */
    glDeleteShader(vs);
    glDeleteShader(fs);

    GLint ok = GL_FALSE;
    glGetProgramiv(st->program, GL_LINK_STATUS, &ok);
    if (!ok) {
        char log[512];
        GLsizei n = 0;
        glGetProgramInfoLog(st->program, sizeof(log), &n, log);
        fprintf(stderr,
                "wl-screenhack: program link failed (%" PRIu32 " bytes): %.*s\n",
                (uint32_t)n, (int)n, log);
        exit(1);
    }

    st->u_angle_loc = glGetUniformLocation(st->program, "u_angle");
    st->u_time_loc  = glGetUniformLocation(st->program, "u_time");

    glGenBuffers(1, &st->vbo);
    DIE(st->vbo, (GLuint)0, "glGenBuffers returned 0");
    glBindBuffer(GL_ARRAY_BUFFER, st->vbo);
    glBufferData(GL_ARRAY_BUFFER, sizeof(k_triangle_verts),
                 k_triangle_verts, GL_STATIC_DRAW);
    glBindBuffer(GL_ARRAY_BUFFER, 0);
    return 0;
}

static void triangle_reshape(struct effect *e, int width, int height) {
    /* Viewport is set in the per-frame draw, not here, so that a future
     * multi-pass effect can override it. Width/height are propagated so
     * a future effect can do aspect-correct ortho projection here. */
    (void)e;
    (void)width;
    (void)height;
}

static void triangle_draw(struct effect *e, double now_seconds) {
    struct triangle_state *st = e->user;

    /* Background: deep gray. The composit's overlay layer composites this
     * over whatever's underneath; we still clear so the framebuffer state
     * is well-defined. */
    glClearColor(0.06f, 0.06f, 0.08f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT);

    /* Wrap-safe rotation: fmod() guarantees the result is in [0, 2π) and
     * is well-behaved over arbitrarily long uptimes. Period: 12 s. */
    const float two_pi = 6.28318530717958647692f;
    float angle = (float)fmod(now_seconds * (two_pi / 12.0), two_pi);
    if (angle < 0.0f) angle += two_pi;

    glUseProgram(st->program);
    glUniform1f(st->u_angle_loc, angle);
    glUniform1f(st->u_time_loc,  (float)now_seconds);

    glBindBuffer(GL_ARRAY_BUFFER, st->vbo);
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE,
                          (GLsizei)(2 * sizeof(GLfloat)), (void *)0);
    glDrawArrays(GL_TRIANGLES, 0, 3);
    glDisableVertexAttribArray(0);
    glBindBuffer(GL_ARRAY_BUFFER, 0);
}

static void triangle_free(struct effect *e) {
    struct triangle_state *st = e->user;
    if (!st) return;
    if (st->vbo)     glDeleteBuffers(1, &st->vbo);
    if (st->program) glDeleteProgram(st->program);
    st->vbo = 0;
    st->program = 0;
}

static struct triangle_state g_triangle_state;
static struct effect g_test_triangle_effect = {
    .name    = "test-triangle",
    .init    = triangle_init,
    .reshape = triangle_reshape,
    .draw    = triangle_draw,
    .free    = triangle_free,
    .user    = &g_triangle_state,
};

/* -------------------------------------------------------------------------- */
/* Application state                                                          */
/* -------------------------------------------------------------------------- */

struct app {
    /* Wayland */
    struct wl_display              *display;
    struct wl_registry             *registry;
    struct wl_compositor           *compositor;
    struct wl_seat                 *seat;
    struct wl_keyboard             *keyboard;
    struct wl_output               *output;          /* first one we see, may be NULL */
    struct zwlr_layer_shell_v1     *layer_shell;
    struct wl_surface              *surface;
    struct zwlr_layer_surface_v1   *layer_surface;

    /* EGL */
    struct wl_egl_window  *egl_window;
    EGLDisplay             egl_display;
    EGLConfig              egl_config;
    EGLSurface             egl_surface;
    EGLContext             egl_context;

    /* Geometry — set on first configure, updated on subsequent ones. */
    int width;
    int height;

    /* Frame-callback bookkeeping */
    struct wl_callback *frame_cb;
    bool frame_in_flight;

    /* Effect */
    struct effect *effect;

    /* Run flag — flipped by signal handler. */
    volatile sig_atomic_t running;

    /* Surface has been ACKed and resources are live. Until this is set,
     * the frame callback should not request a redraw (there is no
     * EGL surface yet). */
    bool configured;
};

/* -------------------------------------------------------------------------- */
/* Signal handling                                                            */
/* -------------------------------------------------------------------------- */

static struct app *g_app_for_signal = NULL;

static void on_signal(int sig) {
    (void)sig;
    if (g_app_for_signal) g_app_for_signal->running = 0;
    /* Re-raise? No — we want the main loop to observe `running == 0` and
     * quit cleanly. */
}

static void install_signals(void) {
    struct sigaction sa;
    memset(&sa, 0, sizeof sa);
    sa.sa_handler = on_signal;
    sigemptyset(&sa.sa_mask);
    /* Block the OTHER signal during handler so we don't reenter. */
    sigaddset(&sa.sa_mask, SIGINT);
    sigaddset(&sa.sa_mask, SIGTERM);
    DIE(sigaction(SIGINT,  &sa, NULL), 0, "sigaction(SIGINT) failed");
    DIE(sigaction(SIGTERM, &sa, NULL), 0, "sigaction(SIGTERM) failed");

    /* Ignore SIGPIPE — we don't write to sockets via fd write paths here,
     * but the compositor connection is a socket and EPIPE is harmless. */
    struct sigaction ign;
    memset(&ign, 0, sizeof ign);
    ign.sa_handler = SIG_IGN;
    sigemptyset(&ign.sa_mask);
    DIE(sigaction(SIGPIPE, &ign, NULL), 0, "sigaction(SIGPIPE) failed");
}

/* -------------------------------------------------------------------------- */
/* Monotonic clock                                                            */
/* -------------------------------------------------------------------------- */

static double monotonic_seconds(void) {
    struct timespec ts;
    /* CLOCK_MONOTONIC is the right choice: not affected by wall-clock
     * changes, always strictly increasing. */
    if (clock_gettime(CLOCK_MONOTONIC, &ts) != 0) {
        fprintf(stderr, "wl-screenhack: clock_gettime(CLOCK_MONOTONIC) failed\n");
        exit(1);
    }
    return (double)ts.tv_sec + (double)ts.tv_nsec * 1e-9;
}

/* -------------------------------------------------------------------------- */
/* Wayland registry binding                                                   */
/* -------------------------------------------------------------------------- */

static void registry_handle_global(void *data,
                                   struct wl_registry *registry,
                                   uint32_t name,
                                   const char *interface,
                                   uint32_t version) {
    (void)version;
    struct app *app = data;

    if (strcmp(interface, wl_compositor_interface.name) == 0) {
        app->compositor =
            wl_registry_bind(registry, name, &wl_compositor_interface, 4);
    } else if (strcmp(interface, wl_seat_interface.name) == 0) {
        /* Request v7 — current wl_seat is at v11 but v7 is sufficient for
         * get_keyboard + capabilities, and avoids dragging in newer
         * event signatures we don't use. */
        app->seat = wl_registry_bind(registry, name, &wl_seat_interface, 7);
    } else if (strcmp(interface, wl_output_interface.name) == 0) {
        if (app->output == NULL) {
            /* Bind at least one output so the layer-shell has a target.
             * v4 is the current stable. */
            app->output =
                wl_registry_bind(registry, name, &wl_output_interface, 4);
        }
    } else if (strcmp(interface, zwlr_layer_shell_v1_interface.name) == 0) {
        /* v4 of wlr-layer-shell is sufficient for our feature set; v5
         * adds the on_demand keyboard interactivity we don't use. */
        app->layer_shell =
            wl_registry_bind(registry, name,
                             &zwlr_layer_shell_v1_interface, 4);
    } else if (strcmp(interface, xdg_wm_base_interface.name) == 0) {
        /* xdg-shell is bound here to prove the protocol XML is being
         * compiled into the binary; we don't keep the pointer because
         * the layer-shell gives us everything we need. Future rounds
         * (e.g. a file-chooser dialog) may stash this in app->xdg_wm. */
        struct xdg_wm_base *xdg = wl_registry_bind(registry, name,
                                                  &xdg_wm_base_interface, 1);
        if (xdg) xdg_wm_base_destroy(xdg);
    }
}

static void registry_handle_global_remove(void *data,
                                          struct wl_registry *registry,
                                          uint32_t name) {
    (void)data; (void)registry; (void)name;
    /* The compositor is required to keep globals alive for the duration of
     * the connection, so we don't need to do anything here. */
}

static const struct wl_registry_listener registry_listener = {
    .global        = registry_handle_global,
    .global_remove = registry_handle_global_remove,
};

/* -------------------------------------------------------------------------- */
/* wl_keyboard — quit on any key press                                        */
/* -------------------------------------------------------------------------- */

static void keyboard_handle_key(void *data,
                                struct wl_keyboard *keyboard,
                                uint32_t serial,
                                uint32_t time,
                                uint32_t key,
                                uint32_t state) {
    (void)keyboard; (void)serial; (void)time;
    struct app *app = data;
    if (state == WL_KEYBOARD_KEY_STATE_PRESSED) {
        (void)key;
        app->running = 0;
    }
}

static void keyboard_handle_enter(void *data,
                                  struct wl_keyboard *keyboard,
                                  uint32_t serial,
                                  struct wl_surface *surface,
                                  struct wl_output *output) {
    (void)data; (void)keyboard; (void)serial; (void)surface; (void)output;
}
static void keyboard_handle_leave(void *data,
                                  struct wl_keyboard *keyboard,
                                  uint32_t serial,
                                  struct wl_surface *surface) {
    (void)data; (void)keyboard; (void)serial; (void)surface;
}
static void keyboard_handle_keymap(void *data,
                                   struct wl_keyboard *keyboard,
                                   uint32_t format,
                                   int fd,
                                   uint32_t size) {
    (void)data; (void)keyboard; (void)format; (void)fd; (void)size;
}
static void keyboard_handle_modifiers(void *data,
                                      struct wl_keyboard *keyboard,
                                      uint32_t serial,
                                      uint32_t mods_depressed,
                                      uint32_t mods_latched,
                                      uint32_t mods_locked,
                                      uint32_t group) {
    (void)data; (void)keyboard; (void)serial;
    (void)mods_depressed; (void)mods_latched; (void)mods_locked; (void)group;
}
static void keyboard_handle_repeat_info(void *data,
                                        struct wl_keyboard *keyboard,
                                        int rate,
                                        int delay) {
    (void)data; (void)keyboard; (void)rate; (void)delay;
}

static const struct wl_keyboard_listener keyboard_listener = {
    .key          = keyboard_handle_key,
    .enter        = keyboard_handle_enter,
    .leave        = keyboard_handle_leave,
    .keymap       = keyboard_handle_keymap,
    .modifiers    = keyboard_handle_modifiers,
    .repeat_info  = keyboard_handle_repeat_info,
};

static void seat_handle_capabilities(void *data,
                                     struct wl_seat *seat,
                                     enum wl_seat_capability caps) {
    (void)seat;
    struct app *app = data;
    if ((caps & WL_SEAT_CAPABILITY_KEYBOARD) && app->keyboard == NULL) {
        app->keyboard = wl_seat_get_keyboard(app->seat);
        if (!app->keyboard) {
            fprintf(stderr,
                    "wl-screenhack: wl_seat_get_keyboard returned NULL\n");
            exit(1);
        }
        wl_keyboard_add_listener(app->keyboard, &keyboard_listener, app);
    } else if (!(caps & WL_SEAT_CAPABILITY_KEYBOARD) && app->keyboard != NULL) {
        wl_keyboard_release(app->keyboard);
        app->keyboard = NULL;
    }
}

static const struct wl_seat_listener seat_listener = {
    .capabilities = seat_handle_capabilities,
};

/* -------------------------------------------------------------------------- */
/* zwlr_layer_surface_v1 — configure / closed                                  */
/* -------------------------------------------------------------------------- */

static void layer_surface_handle_configure(void *data,
                                           struct zwlr_layer_surface_v1 *ls,
                                           uint32_t serial,
                                           uint32_t w,
                                           uint32_t h) {
    struct app *app = data;

    /* ACK unconditionally — required for every configure, including the
     * ones we get after we've already drawn. */
    zwlr_layer_surface_v1_ack_configure(ls, serial);

    if (w == 0 || h == 0) {
        /* The compositor may legitimately pass 0 in some configurations
         * (e.g. an output is being hot-plugged). Keep the previous
         * surface size in that case; the next configure will fix it. */
        return;
    }

    if (app->configured && (w != (uint32_t)app->width || h != (uint32_t)app->height)) {
        /* Resize the EGL window BEFORE the next frame, and notify the
         * effect so it can update projection state. */
        wl_egl_window_resize(app->egl_window, (int)w, (int)h);
        app->width  = (int)w;
        app->height = (int)h;
        app->effect->reshape(app->effect, app->width, app->height);
    } else if (!app->configured) {
        /* First configure — set up EGL window + surface, then context. */
        app->width  = (int)w;
        app->height = (int)h;
        app->egl_window = wl_egl_window_create(app->surface, app->width, app->height);
        if (!app->egl_window) {
            fprintf(stderr,
                    "wl-screenhack: wl_egl_window_create failed for %dx%d\n",
                    app->width, app->height);
            exit(1);
        }

        app->egl_surface =
            eglCreateWindowSurface(app->egl_display, app->egl_config,
                                   (EGLNativeWindowType)app->egl_window, NULL);
        if (app->egl_surface == EGL_NO_SURFACE) {
            fprintf(stderr,
                    "wl-screenhack: eglCreateWindowSurface failed (0x%x)\n",
                    (unsigned int)eglGetError());
            exit(1);
        }

        DIE(eglMakeCurrent(app->egl_display, app->egl_surface,
                           app->egl_surface, app->egl_context),
            EGL_TRUE, "eglMakeCurrent failed");

        /* Now that GL is current, initialize the effect (loads shaders,
         * uploads geometry). */
        if (app->effect->init(app->effect) != 0) {
            fprintf(stderr, "wl-screenhack: effect '%s' init failed\n",
                    app->effect->name);
            exit(1);
        }
        app->effect->reshape(app->effect, app->width, app->height);
        app->configured = true;
    }
}

static void layer_surface_handle_closed(void *data,
                                        struct zwlr_layer_surface_v1 *ls) {
    (void)ls;
    struct app *app = data;
    app->running = 0;
}

static const struct zwlr_layer_surface_v1_listener layer_surface_listener = {
    .configure = layer_surface_handle_configure,
    .closed    = layer_surface_handle_closed,
};

/* -------------------------------------------------------------------------- */
/* Frame callback — the actual render loop                                    */
/* -------------------------------------------------------------------------- */

static void frame_handle_done(void *data, struct wl_callback *cb, uint32_t time);
static const struct wl_callback_listener frame_listener = {
    .done = frame_handle_done,
};

static void request_frame(struct app *app) {
    if (app->frame_in_flight || !app->configured) return;
    app->frame_cb = wl_surface_frame(app->surface);
    if (!app->frame_cb) {
        fprintf(stderr,
                "wl-screenhack: wl_surface_frame returned NULL\n");
        app->running = 0;
        return;
    }
    wl_callback_add_listener(app->frame_cb, &frame_listener, app);
    app->frame_in_flight = true;
    /* We commit at swap time so the buffer is presented; eglSwapBuffers
     * on a Wayland window surface performs the attach + commit internally. */
}

static void frame_handle_done(void *data, struct wl_callback *cb, uint32_t time) {
    (void)time;
    struct app *app = data;

    wl_callback_destroy(cb);
    app->frame_cb = NULL;
    app->frame_in_flight = false;

    if (!app->running) return;

    /* glViewport uses the latest configured size. */
    glViewport(0, 0, app->width, app->height);

    app->effect->draw(app->effect, monotonic_seconds());

    if (!eglSwapBuffers(app->egl_display, app->egl_surface)) {
        fprintf(stderr,
                "wl-screenhack: eglSwapBuffers failed (0x%x)\n",
                (unsigned int)eglGetError());
        app->running = 0;
        return;
    }

    request_frame(app);
}

/* -------------------------------------------------------------------------- */
/* Wayland / EGL / GL initialization                                          */
/* -------------------------------------------------------------------------- */

/*
 * Choose an EGL config matching: ES2-capable, RGBA8, double-buffered,
 * with both window AND pbuffer surface types (the latter required by
 * EGL_KHR_surfaceless_context on some drivers; harmless to include).
 */
/*
 * Choose an EGL config: ES2-capable, RGBA8888, double-buffered window
 * surface. We don't request depth/stencil buffers — the test effect
 * uses 2D shapes only. Future rounds (port xscreensaver hacks) may
 * need to add EGL_DEPTH_SIZE=16 here.
 */
static EGLConfig choose_egl_config(EGLDisplay dpy) {
    EGLint cfg_attr[] = {
        EGL_SURFACE_TYPE,        EGL_WINDOW_BIT,
        EGL_RENDERABLE_TYPE,     EGL_OPENGL_ES2_BIT,
        EGL_RED_SIZE,            8,
        EGL_GREEN_SIZE,          8,
        EGL_BLUE_SIZE,           8,
        EGL_ALPHA_SIZE,          8,
        EGL_DEPTH_SIZE,          0,
        EGL_STENCIL_SIZE,        0,
        EGL_NONE,
    };
    EGLint num = 0;
    DIE(eglChooseConfig(dpy, cfg_attr, NULL, 0, &num), EGL_TRUE,
        "eglChooseConfig (probe) failed");
    if (num < 1) {
        fprintf(stderr,
                "wl-screenhack: no EGL configs match requested attributes\n");
        exit(1);
    }
    EGLConfig cfg;
    DIE(eglChooseConfig(dpy, cfg_attr, &cfg, 1, &num), EGL_TRUE,
        "eglChooseConfig failed");
    if (num < 1) {
        fprintf(stderr,
                "wl-screenhack: eglChooseConfig returned 0 matching configs on select\n");
        exit(1);
    }
    return cfg;
}

static void init_wayland(struct app *app) {
    app->display = wl_display_connect(NULL);
    if (!app->display) {
        fprintf(stderr,
                "wl-screenhack: wl_display_connect failed — is WAYLAND_DISPLAY set?\n");
        exit(1);
    }

    app->registry = wl_display_get_registry(app->display);
    if (!app->registry) {
        fprintf(stderr, "wl-screenhack: wl_display_get_registry returned NULL\n");
        exit(1);
    }

    /* The registry listener will fill compositor / seat / output / layer_shell. */
    wl_registry_add_listener(app->registry, &registry_listener, app);

    /* First roundtrip: deliver globals. */
    DIE(wl_display_roundtrip(app->display), 0,
        "wl_display_roundtrip (registry bind) failed");

    if (!app->compositor) {
        fprintf(stderr, "wl-screenhack: wl_compositor not advertised by compositor\n");
        exit(1);
    }
    if (!app->layer_shell) {
        fprintf(stderr,
                "wl-screenhack: zwlr_layer_shell_v1 not advertised — "
                "is the compositor wlr-based?\n");
        exit(1);
    }
    if (!app->seat) {
        fprintf(stderr, "wl-screenhack: wl_seat not advertised\n");
        exit(1);
    }
    /* Seat listener must be added AFTER we have a seat — the capabilities
     * event fires when we roundtrip again below. */
    wl_seat_add_listener(app->seat, &seat_listener, app);

    /* Bind keyboard if it's already present. */
    DIE(wl_display_roundtrip(app->display), 0,
        "wl_display_roundtrip (seat caps) failed");

    /* Set up the EGL *display / config / context* before creating the
     * layer surface. The actual window surface and makeCurrent happen
     * later — in the first configure callback — once we know the
     * compositor's negotiated width/height. */
    init_egl(app);

    /* Create the surface + layer surface. */
    app->surface = wl_compositor_create_surface(app->compositor);
    if (!app->surface) {
        fprintf(stderr, "wl-screenhack: wl_compositor_create_surface returned NULL\n");
        exit(1);
    }

    app->layer_surface = zwlr_layer_shell_v1_get_layer_surface(
        app->layer_shell, app->surface, app->output,
        ZWLR_LAYER_SHELL_V1_LAYER_OVERLAY, "wl-screenhack");
    if (!app->layer_surface) {
        fprintf(stderr, "wl-screenhack: zwlr_layer_shell_v1_get_layer_surface returned NULL\n");
        exit(1);
    }

    /* Anchor to all four edges — we want full-screen overlay. */
    zwlr_layer_surface_v1_set_anchor(app->layer_surface,
        ZWLR_LAYER_SURFACE_V1_ANCHOR_TOP
        | ZWLR_LAYER_SURFACE_V1_ANCHOR_BOTTOM
        | ZWLR_LAYER_SURFACE_V1_ANCHOR_LEFT
        | ZWLR_LAYER_SURFACE_V1_ANCHOR_RIGHT);

    /* exclusive_zone=-1 means: this surface is NOT used to reserve space
     * for other layers — it may overlap them. */
    zwlr_layer_surface_v1_set_exclusive_zone(app->layer_surface, -1);

    /* We want all key events so we can quit on any key press. ON means
     * "exclusive" — wlr-layer-shell will route keyboard focus to us. */
    zwlr_layer_surface_v1_set_keyboard_interactivity(
        app->layer_surface, ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_ON);

    zwlr_layer_surface_v1_add_listener(app->layer_surface,
                                       &layer_surface_listener, app);

    /* Per protocol: first commit must be with no buffer attached, after
     * which the compositor delivers a configure event. */
    wl_surface_commit(app->surface);

    /* Deliver the configure event. */
    DIE(wl_display_roundtrip(app->display), 0,
        "wl_display_roundtrip (configure) failed");

    if (!app->configured) {
        fprintf(stderr,
                "wl-screenhack: layer_surface never configured after first commit\n");
        exit(1);
    }
}

/*
 * Initialize the EGL *display*, pick a config, and create a GLES2 context.
 *
 * Called from init_wayland() after the Wayland globals are bound but before
 * the layer surface is created. The EGL *window surface* and eglMakeCurrent
 * are NOT done here — those happen inside the layer_surface.configure
 * callback, once we know the compositor-negotiated width/height.
 */
static void init_egl(struct app *app) {
    /* eglGetPlatformDisplay is the modern, non-deprecated path; on EGL
     * 1.5 it is core; on EGL 1.4 it's available via EGL_EXT_platform_wayland.
     * Mesa advertises it on Wayland. */
    app->egl_display = eglGetPlatformDisplay(EGL_PLATFORM_WAYLAND_KHR,
                                             app->display, NULL);
    if (app->egl_display == EGL_NO_DISPLAY) {
        /* Fallback for very old EGL: try the legacy eglGetDisplay. */
        app->egl_display = eglGetDisplay((EGLNativeDisplayType)app->display);
        if (app->egl_display == EGL_NO_DISPLAY) {
            fprintf(stderr,
                    "wl-screenhack: eglGetPlatformDisplay(EGL_PLATFORM_WAYLAND_KHR) failed\n");
            exit(1);
        }
    }

    EGLint major = 0, minor = 0;
    if (!eglInitialize(app->egl_display, &major, &minor)) {
        fprintf(stderr, "wl-screenhack: eglInitialize failed (0x%x)\n",
                (unsigned int)eglGetError());
        exit(1);
    }

    app->egl_config = choose_egl_config(app->egl_display);

    /* Bind GLES2 — we ask for an OpenGL ES 2.0 context. */
    EGLint ctx_attr[] = {
        EGL_CONTEXT_CLIENT_VERSION, 2,
        EGL_NONE,
    };
    app->egl_context =
        eglCreateContext(app->egl_display, app->egl_config,
                         EGL_NO_CONTEXT, ctx_attr);
    if (app->egl_context == EGL_NO_CONTEXT) {
        fprintf(stderr, "wl-screenhack: eglCreateContext (GLES2) failed (0x%x)\n",
                (unsigned int)eglGetError());
        exit(1);
    }
}

/* -------------------------------------------------------------------------- */
/* Clean shutdown                                                             */
/* -------------------------------------------------------------------------- */

static void app_fini(struct app *app) {
    /* Idempotent — safe to call from error paths. */

    if (app->frame_cb) {
        wl_callback_destroy(app->frame_cb);
        app->frame_cb = NULL;
    }

    if (app->effect && app->configured) {
        app->effect->free(app->effect);
    }

    if (app->egl_context != EGL_NO_CONTEXT) {
        eglMakeCurrent(app->egl_display, EGL_NO_SURFACE, EGL_NO_SURFACE,
                       EGL_NO_CONTEXT);
        eglDestroyContext(app->egl_display, app->egl_context);
        app->egl_context = EGL_NO_CONTEXT;
    }
    if (app->egl_surface != EGL_NO_SURFACE) {
        eglDestroySurface(app->egl_display, app->egl_surface);
        app->egl_surface = EGL_NO_SURFACE;
    }
    if (app->egl_window) {
        wl_egl_window_destroy(app->egl_window);
        app->egl_window = NULL;
    }
    if (app->egl_display != EGL_NO_DISPLAY) {
        eglTerminate(app->egl_display);
        app->egl_display = EGL_NO_DISPLAY;
    }

    if (app->keyboard)  { wl_keyboard_release(app->keyboard);  app->keyboard  = NULL; }
    if (app->layer_surface) {
        zwlr_layer_surface_v1_destroy(app->layer_surface);
        app->layer_surface = NULL;
    }
    if (app->surface)   { wl_surface_destroy(app->surface);   app->surface   = NULL; }
    if (app->layer_shell) { zwlr_layer_shell_v1_destroy(app->layer_shell); app->layer_shell = NULL; }
    if (app->seat)        { wl_seat_release(app->seat);             app->seat        = NULL; }
    if (app->output)      { wl_output_release(app->output);         app->output      = NULL; }
    if (app->compositor)  { wl_compositor_destroy(app->compositor); app->compositor  = NULL; }
    if (app->registry)    { wl_registry_destroy(app->registry);    app->registry    = NULL; }
    if (app->display)     { wl_display_disconnect(app->display);   app->display     = NULL; }
}

/* -------------------------------------------------------------------------- */
/* main                                                                       */
/* -------------------------------------------------------------------------- */

/* atexit-cleanup: app_fini is idempotent (everything it touches is
 * NULLed/NO_*_-checked), so it's safe to call from any exit path —
 * error paths via the DIE macro, signal-handler-caused exits, normal
 * returns from main. Registered before any resource acquisition. */
static void atexit_app_fini(void) {
    if (g_app_for_signal) {
        app_fini(g_app_for_signal);
        g_app_for_signal = NULL;
    }
}

int main(void) {
    struct app app;
    memset(&app, 0, sizeof app);
    app.egl_display = EGL_NO_DISPLAY;
    app.egl_surface = EGL_NO_SURFACE;
    app.egl_context = EGL_NO_CONTEXT;
    app.running     = 1;
    app.effect      = &g_test_triangle_effect;

    g_app_for_signal = &app;
    if (atexit(atexit_app_fini) != 0) {
        fprintf(stderr, "wl-screenhack: atexit registration failed\n");
        exit(1);
    }
    install_signals();

    init_wayland(&app);
    /* EGL display/config/context are initialized inside init_wayland,
     * before the layer surface is created; the window surface and
     * makeCurrent happen inside the first configure callback. */

    /* Prime the render loop: draw one frame and swap so the compositor
     * has a buffer to present; this causes the frame callback we just
     * requested to actually fire on the next compositor cycle. */
    glViewport(0, 0, app.width, app.height);
    app.effect->draw(app.effect, monotonic_seconds());
    if (!eglSwapBuffers(app.egl_display, app.egl_surface)) {
        fprintf(stderr,
                "wl-screenhack: initial eglSwapBuffers failed (0x%x)\n",
                (unsigned int)eglGetError());
        exit(1);
    }
    request_frame(&app);

    /* Main loop.
     *
     * We use the wl_display_prepare_read / poll / read_events /
     * dispatch_pending pattern so that SIGINT/SIGTERM wake the poll
     * immediately (instead of being swallowed by libwayland's internal
     * EINTR retry loop). Plain wl_display_dispatch would also work but
     * could keep us blocked for an arbitrary time after a signal.
     */
    while (app.running) {
        while (wl_display_prepare_read(app.display) != 0) {
            /* Events already queued: dispatch them first. */
            if (wl_display_dispatch_pending(app.display) < 0) {
                fprintf(stderr,
                        "wl-screenhack: wl_display_dispatch_pending error: %s\n",
                        errno ? strerror(errno) : "unknown");
                app.running = 0;
                break;
            }
        }
        if (!app.running) break;

        /* Block until the Wayland fd is readable or we're interrupted
         * by a signal. POLLIN fires on compositor events. */
        struct pollfd pfd = {
            .fd     = wl_display_get_fd(app.display),
            .events = POLLIN,
        };
        int n = poll(&pfd, 1, -1);
        if (n < 0) {
            if (errno == EINTR) {
                /* Signal — drop out of prepare_read and re-check running. */
                wl_display_cancel_read(app.display);
                continue;
            }
            fprintf(stderr,
                    "wl-screenhack: poll error: %s\n", strerror(errno));
            wl_display_cancel_read(app.display);
            app.running = 0;
            break;
        }
        if (n == 0) continue; /* shouldn't happen with -1 timeout, but be safe */

        /* Read events from the fd, then dispatch. */
        if (wl_display_read_events(app.display) < 0) {
            fprintf(stderr,
                    "wl-screenhack: wl_display_read_events error: %s\n",
                    errno ? strerror(errno) : "unknown");
            app.running = 0;
            break;
        }
        if (wl_display_dispatch_pending(app.display) < 0) {
            fprintf(stderr,
                    "wl-screenhack: wl_display_dispatch_pending error: %s\n",
                    errno ? strerror(errno) : "unknown");
            app.running = 0;
            break;
        }
    }

    /* Flush any pending outgoing requests before tearing down.
     * atexit_app_fini (registered below) will release all resources. */
    if (app.display) wl_display_roundtrip(app.display);

    return 0;
    /* atexit handler runs app_fini. */
}